### ISSUE TITLE
HttpClientFactory DI Errors

### ISSUE THREAD

**Issue by mayoatte** [Azure/Azure-Functions#1011]
Hey folks,

I'm trying to use the HttpClientFactory introduced in .Net Core 2.1 in an Azure Functions (v2). I was able to write all the code, and everything compiles. However, the runtime  is not able to resolve the newly registered HttpClientFactory.

Here's the error I get.

![image](https://user-images.githubusercontent.com/29760620/47768016-319e3800-dca4-11e8-8a2a-c13a0a09cb68.png)

And this is how I am registering it in the Startup class.

![image](https://user-images.githubusercontent.com/29760620/47768055-55617e00-dca4-11e8-9589-192584820323.png)

Any ideas on what could be wrong? The same exact code runs fines in a unit test (creating a new ServiceCollection, and performing the lines above) so it appears to be something wrong with the runtime. 

Help.

Edit: Stack Trace below

`   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateEnumerable(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Client.Iocp.Project.TelemetryAgent.Startup.Configure(IWebJobsBuilder builder) in C:\Code\CLIENTAzure\client-iocp-framework\TelemetryAgent\TelemetryAgent\Startup.cs:line 32`

**Comment by ColbyTresness** [comment]
We're working on making DI easier for users, but until then, this is unsupported. It might work, but I'd recommend holding off until we add this officially.

**Comment by ColbyTresness** [comment]
@fabiocav to answer above. Also, this is one of the issues I wanted to transfer to the Host repo.

**Comment by fabiocav** [comment]
There are two distinct tasks that will address this
  1 - Built in DI support (currently in progress) (https://github.com/Azure/azure-functions-host/issues/3736)
  2 - Built in support for HttpClientFactory (planned, but not yet started, created https://github.com/Azure/azure-functions-host/issues/3737 to track)

That said, the exception and stack you have above do look odd. Do you have a simple repro you can share on GitHub? Is the stack for the `null` ref you're seeing at indexing?

**Comment by mayoatbm** [comment]
@fabiocav 

Repro below. I'm sorry it took so long to get it up here.

https://github.com/mayoatbm/azfunc-hcf-repro
