### ISSUE TITLE
activityTrigger and orchestrationTrigger are not registered on Azure

### ISSUE THREAD

**Issue by juchom** [Azure/Azure-Functions#1186]
I have a project with durable functions that works fine locally but not on Azure.

The starter function (TimerTrigger) works fine locally and on Azure.

The orchestrator and activities are working fine locally but on the portal on Azure I have this error:

> The binding type(s) 'orchestrationTrigger' are not registered. Please ensure the type is correct and the binding extension is installed. 
> The binding type(s) 'activityTrigger' are not registered. Please ensure the type is correct and the binding extension is installed. 

I've tried with:
Microsoft.Azure.WebJobs.Extensions.DurableTask v1.8.0 & v1.7.1
Microsoft.NET.Sdk.Functions 1.0.26 & 1.0.24
FUNCTIONS_EXTENSION_VERSION ~2 & 2.0.12342.0

Any idea on where I should start looking?

EDIT:
Connecting to remote logging with VS2019:

> Application:2019-04-08T07:55:21.120 [Error] Error indexing method 'MyFunctionStarter'
> Application:Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexingException : Error indexing method 'MyFunctionStarter' ---> System.InvalidOperationException : Cannot bind parameter 'starter' to type DurableOrchestrationClient. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
> Application:   at async Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsyncCore(MethodInfo method,IFunctionIndexCollector index,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs : 242
> Application:   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> Application:   at async Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsync(MethodInfo method,IFunctionIndexCollector index,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs : 137 
> Application:   End of inner exception
> Application:   at async Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsync(MethodInfo method,IFunctionIndexCollector index,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs : 145
> Application:   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> Application:   at async Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexTypeAsync(Type type,IFunctionIndexCollector index,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs : 73
> Application:2019-04-08T07:55:21.173 [Warning] Function 'MyFunctionStarter' failed indexing and will be disabled.
> Application:2019-04-08T07:55:21.173 [Warning] No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).

```
public static class MyFunctionStarter
{
        [FunctionName("MyFunctionStarter")]
        public static async Task Run([TimerTrigger("0 30 5 * * *")]TimerInfo myTimer,
            [OrchestrationClient] DurableOrchestrationClient starter)
    {
    }
}
```

The function body is empty. Without [OrchestrationClient] DurableOrchestrationClient starter, the function works, as soon as I add it doesn't work anymore.

Here is the csproj:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <AzureFunctionsVersion>v2</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="1.8.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.26" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

**Comment by juchom** [comment]
Wrong repo, sorry for that: moved to https://github.com/Azure/azure-functions-durable-extension/issues/692
