### ISSUE TITLE
Zip deployment failure on Linux consumption

### ISSUE THREAD

**Issue by yokawasa** [Azure/Azure-Functions#1190]
I've tried to deploy my python functions project to Azure from a Zip but I failed with the following errors:

```
$ az functionapp deployment source config-zip --name yoichikaazfuncv2linux001 --resource-group RG-azfuncv2 --src functions.zip

Getting scm site credentials for zip deployment
Failed to retrieve Scm Uri
Traceback (most recent call last):
  File "/Users/yoichika/dev/venv3.6/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/Users/yoichika/dev/venv3.6/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in execute
    raise ex
  File "/Users/yoichika/dev/venv3.6/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 386, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/Users/yoichika/dev/venv3.6/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 379, in _run_job
    six.reraise(*sys.exc_info())
  File "/Users/yoichika/dev/venv3.6/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/yoichika/dev/venv3.6/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 356, in _run_job
    result = cmd_copy(params)
  File "/Users/yoichika/dev/venv3.6/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 171, in __call__
    return self.handler(*args, **kwargs)
  File "/Users/yoichika/dev/venv3.6/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 452, in default_command_handler
    return op(**command_args)
  File "/Users/yoichika/dev/venv3.6/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 274, in enable_zip_deploy
    scm_url = _get_scm_url(cmd, resource_group_name, name, slot)
  File "/Users/yoichika/dev/venv3.6/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 1375, in _get_scm_url
    raise ValueError('Failed to retrieve Scm Uri')
ValueError: Failed to retrieve Scm Uri
```
Is Zip deployment supported on Linux consumption?

## Environment info
- Pricing tier:  `EastUSLinuxDynamicPlan (Consumption)`
- Functions Version: 2.0
- Worker: Python
- azure CLI version: 2.0.60
- Resource Group: RG-azfuncv2
- Functions app:  yoichikaazfuncv2linux001

**Comment by yokawasa** [comment]
This is the same issue as Azure/azure-functions-core-tools#1173

**Comment by balag0** [comment]
@yokawasa  this is not the same as https://github.com/Azure/azure-functions-core-tools/issues/1173
Linux consumption does not support zip deployment currently. 

Please try https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-azure-function-azure-cli-linux#deploy-the-function-app-project-to-azure instead.

**Comment by yokawasa** [comment]
@balag0 Thanks! I understood it. 
Any relevant thread on Linux consumption supports zip deployment so that I can track?

**Comment by balag0** [comment]
I created this tracking issue - https://github.com/Azure/Azure-Functions/issues/1200
Thanks
