### ISSUE TITLE
Azure Functions throw TaskCanceledException

### ISSUE THREAD

**Issue by vijayrkn** [Azure/Azure-Functions#1210]
Create new Azure Function 2.0 project with an HttpTrigger function. Run it locally. Open the URL to trigger the funtion

Systems.Threading.Tasks.TaskCanceledException

in System.Private.CoreLib.dll

"A task was cancelled"

This happens for each request.

More details in this bug report : https://developercommunity.visualstudio.com/content/problem/549316/azure-functions-throw-taskcanceledexception.html

**Comment by ColbyTresness** [comment]
@Francisco-Gamino can you investigate?

**Comment by GuilhermeMorais** [comment]
I got the same error, in my case the project was created using the cmd: func init.
  This error happens while debugging or when you publish to Azure.

Error detail:
```C#
System.Threading.Tasks.TaskCanceledException
  HResult=0x8013153B
  Message=A task was canceled.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.MetricsEventManager.FunctionActivityTracker.<<-ctor>b__8_0>d.MoveNext() in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Diagnostics\MetricsEventManager.cs:line 341
```

**Comment by zorkind** [comment]
Any news on this issue? for me this is happening in 1.0 az function. after it run for some time, exactly 229936ms i don't think this is function timeout, my function is on an app service so the timeout should be zero as default.

**Comment by arby50** [comment]
I can duplicate as well, but calling multiple HTTP clients simultaneously to the same HTTPTrigger.  For example, when starting 20 simultaneous calls, 5 will error with the TaskCanceledException within the first 30 seconds.

**Comment by Francisco-Gamino** [comment]
Hi @ankitkumarr, could you please take a look? If this is not Core-Tools related, we'll move it to the correct repo. Thanks.

**Comment by karinpm** [comment]
I am also experiencing this issue - is there any update?

**Comment by ankitkumarr** [comment]
This looks like a host issue. Moving to that repo.
