### ISSUE TITLE
Exception while using Cosmos Table Api with function v1.0

### ISSUE THREAD

**Issue by pranav1509** [Azure/Azure-Functions#1243]
We are getting below error while using cosmos table api with azure function v1.0

Exception: 
Method not found: 'Void Microsoft.Azure.Documents.Client.DocumentClient..ctor(System.Uri, System.String, Newtonsoft.Json.JsonSerializerSettings, Microsoft.Azure.Documents.Client.ConnectionPolicy, System.Nullable`1<Microsoft.Azure.Documents.ConsistencyLevel>)'.

StackTrace: 
   at Microsoft.Azure.Cosmos.Table.Extensions.TableExtensionExecutor.<>c__DisplayClass19_0`2.<<ExecuteQuerySegmentedInternalAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.Table.Extensions.TableExtensionRetryPolicy.<ExecuteUnderRetryPolicy>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TestFunction.CosmosStorageHelper.<RetrieveFromStorageAsync>d__0`1.MoveNext()

This makes cosmos db unusable with azure function v1.0.

**Comment by ColbyTresness** [comment]
@brettsam for cosmos integration

**Comment by brettsam** [comment]
What version of the Cosmos nugets are you using? My guess is that this is b/c v1 is using an older nuget package built-in.

@ealsur as FYI.

**Comment by ealsur** [comment]
What are the packages being referenced in the project? This sounds like an issue with version mismatch.

If the user is using `Microsoft.Azure.WebJobs.Extensions.DocumentDB` because they are using some Cosmos DB binding / trigger, then that limits them to SDK 1.13.2. This stack trace doesn't seem to be coming from the binding / trigger, so if they want to use a higher SDK, they could reference the SDK directly and remove the `Microsoft.Azure.WebJobs.Extensions.DocumentDB` package reference.

**Comment by pranav1509** [comment]
@ealsur  We are using Microsoft.Azure.Cosmos.Table nuget and we are creating our own storageAccount client. We are not using bindings as such. 

I have tried using several nuget versions starting from latest to the first one , also attempted to use Microsoft.Azure.cosmosDb.table nuget in oder to verify if that works. None of the Nuget worked here.

**Comment by ealsur** [comment]
Could you list all the packages and version? I believe Microsoft.Azure.Cosmos.Table 1.0.1 has a dependency on Newtonsoft.Json >= 10.

Azure Functions V1 has 9.0.0.1 - that can't be worked around, right @brettsam ?

**Comment by FinVamp1** [comment]
Sample from Pranav at https://github.com/FinVamp1/CosmosTableDemo 


    <PackageReference Include="Microsoft.Azure.Cosmos.Table" Version="1.0.1" />

    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.24" />

    <PackageReference Include="Newtonsoft.Json" Version="11.0.2" />

**Comment by ealsur** [comment]
The `Microsoft.NET.Sdk.Functions` package for V1 has a hard dependency on Newtonsoft.Json 9.0.1

![image](https://user-images.githubusercontent.com/1633401/59391331-ce3fb280-8d28-11e9-80ed-1e3212a455d4.png)

See https://github.com/Azure/azure-functions-host/wiki/Assembly-Resolution-in-Azure-Functions#what-are-the-challenges-when-running-on-azure-functions

**Comment by pranav1509** [comment]
@ealsur We use runtime assembly binding to resolve such issues , i did the same for newtonsoft.json assembly as well. It stopped giving me version number mismatch but then i got exception while running my code. You may refer to code which @FinVamp1 has shared.

Also, are you suggesting that it is not at all possible to use Microsoft.Azure.Cosmos.Table Nuget with functions v1.0?

**Comment by ealsur** [comment]
All that I'm saying is that there is a Method Not Found on runtime, that means that binding redirects are not actually redirecting references. The Method that is missing has one of the Newtonsoft.Json classes in the signature. That would mean that, on runtime, the expected signature with the class version, is not found.

Based on the Nuget packages requirements  on the Microsoft.Azure.Cosmos.Table package, and Newtonsoft.Json being locked on 9.0.1 on Functions V1, my guess is that this is not possible. I don't even know how Nuget let you do a restore on that project since it breaks the `Microsoft.NET.Sdk.Functions` dependencies.
![image](https://user-images.githubusercontent.com/1633401/59443348-adbb3b00-8db0-11e9-9601-a5dd322f0559.png)
