### ISSUE TITLE
VS2019 publish fail

### ISSUE THREAD

**Issue by imtrobin** [Azure/Azure-Functions#1303]
I'm opening a new issue as instructed, same issue as to this

https://github.com/Azure/azure-functions-host/issues/4578#issue-456472582

When I publish from VS2019, it fails, and the log file has not much info.

```
System.AggregateException: One or more errors occurred. ---> System.Exception: Publishing failed.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.Publish.Framework.Model.DefaultPublishSteps.<>c__DisplayClass26_0.<IsBuildCompletedSuccessfully>b__2()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Publish.Framework.Model.DefaultPublishSteps.<DefaultCorePublishStep>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Publish.Framework.ViewModel.ProfileSelectorViewModel.<RunPublishTaskAsync>d__205.MoveNext()
---> (Inner Exception #0) System.Exception: Publishing failed.<---
System.Exception: Publishing failed.
```

VS 2019 Pro 16.2.2

I'm not using the new WebDeploy as zip, there is not WEBSITE_RUN_FROM_PACKAGE in my app settings
I have reset "Reset publish credentials". I login from VS2019 Publish manually.
I stopped the App, publish. No go.

I was able to publish before, but I think I was using vs2017 (on a different machine) a while ago.

**Comment by sjkp** [comment]
Is publishing from VS broken in general. I can't publish from VS2017 at all.

**Comment by ColbyTresness** [comment]
I can't repro this (No, publishing isn't broken in general). @soninaren @vijayrkn any thoughts on why this might have failed?

**Comment by vijayrkn** [comment]
Can we go to File -> Account Settings -> All Accounts & see if your account is logged in with the account that has the function app?

**Comment by imtrobin** [comment]
Yes, there is only 1 account there. and I have only 1 azure account only.

**Comment by imtrobin** [comment]
I was just working on another azure function project , where I deployed on vs2017 (on another machine)  without problems. This machine which can't published is a new formatted PC with vs2019 only.

**Comment by indcoder** [comment]
Even I'm facing this issue.

**Comment by vijayrkn** [comment]
Can you please provide some more details? 

Version of VS? 
Version of the function app? 
sample csproj file
Error details etc.

**Comment by indcoder** [comment]
Hi @vijayrkn ,

Version of VS is provided in original message : VS 2019 16.3.5
I'm trying something mentioned in .net conf 2019 
https://github.com/xamarin/XamarinAzureChallenge

**Comment by vijayrkn** [comment]
Are there any errors in the output window?

**Comment by indcoder** [comment]
No errors ....only a warning

![image](https://user-images.githubusercontent.com/2099300/67321625-60549480-f52d-11e9-8e42-3b174c16fcfe.png)

**Comment by Joe-Code** [comment]
Does anyone have a solution for this issue yet?

I'm using Visual Studio 2019, version 16.3.10 and I'm attempting to Publish an Azure Function to Azure. However, I receive the following error "Publishing failed":

11/25/2019 1:30:33 PM
System.AggregateException: One or more errors occurred. ---> System.Exception: Publishing failed.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)   at Microsoft.Publish.Framework.Model.DefaultPublishSteps.<>c__DisplayClass26_0.<IsBuildCompletedSuccessfully>b__2()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Publish.Framework.Model.DefaultPublishSteps.<DefaultCorePublishStep>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Publish.Framework.ViewModel.ProfileSelectorViewModel.<RunPublishTaskAsync>d__202.MoveNext()
---> (Inner Exception #0) System.Exception: Publishing failed.<---

System.Exception: Publishing failed.

**Comment by Joe-Code** [comment]
I found a suggestion [here](https://social.msdn.microsoft.com/Forums/en-US/5b8b7935-4ffd-4b98-9ff9-200e14b4ab4f/cant-publish-azure-function-from-visual-studio-2019) that worked for me.

My fix included, opening the Edit Azure App Service settings dialog from the Publish window, then make sure "WEBSITE_RUN_FROM_PACKAGE" = 0.
