### ISSUE TITLE
Azure function DLLImport error

### ISSUE THREAD

**Issue by truptijogi7** [Azure/Azure-Functions#1630]
I am loading `DLL` with azure function as below syntax

        `public static class IPSGeneratorFunction
        {

        [DllImport(@"D:\\home\\site\\wwwroot\\Generator\\AutoLandmark.dll", EntryPoint = "Run", CallingConvention = CallingConvention.Cdecl)]
        static extern void Run(string args);

        [FunctionName("IPSGeneratorFunction")]
        public async static Task Run([EventGridTrigger]EventGridEvent eventGridEvent, ILogger log)
        {
           Run()
         }`

Function works fine with DLL import on Local machine but failed with below error after publish on Azure.

Any idea what I am missing, 

`Error:System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (0x8007000B)
   at System.Runtime.Loader.AssemblyLoadContext.InternalLoadUnmanagedDllFromPath(String unmanagedDllPath)
   at System.Runtime.Loader.AssemblyLoadContext.LoadUnmanagedDllFromPath(String unmanagedDllPath)
   at Microsoft.Azure.WebJobs.Script.Description.FunctionAssemblyLoadContext.LoadUnmanagedDll(String unmanagedDllName) in D:\a\1\s\src\WebJobs.Script\Description\DotNet\FunctionAssemblyLoadContext.cs:line 366
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUnmanagedDll(String unmanagedDllName, IntPtr gchManagedAssemblyLoadContext)
   at IPS_Wrapper.IPSGeneratorFunction.Run(String args)
   at IPS_Wrapper.GeneratorFunction.Run(EventGridEvent eventGridEvent, ILogger log) in C:\projects\ips_swrapper\IPS_Wrapper\IPSGeneratorFunction.cs:line 37`

**Comment by v-bbalaiagar** [comment]
Hi @truptijogi7 , Apologies for the delayed response, Were you able to find a solution. If you still having this issue persisting, then let us know the repro steps for us to understand the error.

**Comment by v-bbalaiagar** [comment]
Hi @truptijogi7, Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue.
