### ISSUE TITLE
User-assigned managed identity Power Shell Script Execution issue : Could not find file 'C:\home\site\wwwroot\.IdentityService'

### ISSUE THREAD

**Issue by narenkv** [Azure/Azure-Functions#1864]
Hello,

Requirement, We need to execute a PowerShell scripts via Azure Functions without having the login information in the script. So we tried to execute the script via "User-assigned managed identity" . The User assigned managed identity is been given contributor role at the the subscription level. so that means it has the maximum privileges.

Following the the script which we are executing

$nonprodRespourceGroups = (Get-AzResourceGroup -Tag @{'ApmID' = 'XXXXXX' })

Even though the "User-assigned managed identity" has contributor role at Subscription level it throws following error 

However when the same code is executed using System assigned managed identity. The script executes without any issues. 

Error Log  ----------------------->
Connected!
2021-03-10T20:34:09  Welcome, you are now connected to log-streaming service. The default timeout is 2 hours. Change the timeout with the App Setting SCM_LOGSTREAM_TIMEOUT (in seconds).
2021-03-10T20:34:20.146 [Information] Executing 'Functions.func-UserIdenityTest' (Reason='This function was programmatically called via the host APIs.', Id=da3303b3-d3bd-453d-bd93-05e5ace13cee)
2021-03-10T20:34:27.648 [Warning] WARNING: INITIALIZATION: Fallback context save mode to process because of error during checking token cache persistence: Could not find file 'C:\home\site\wwwroot\.IdentityService'..
2021-03-10T20:34:29.144 [Warning] WARNING: Unable to acquire token for tenant 'organizations'
2021-03-10T20:34:30.017 [Error] ERROR: ManagedIdentityCredential authentication failed: Service request failed.Status: 400 (Bad Request)Headers:Date: Wed, 10 Mar 2021 20:34:28 GMTContent-Length: 133Exception             :Type           : Azure.Identity.AuthenticationFailedExceptionTargetSite     :Name          : FailWrapAndThrowDeclaringType : Azure.Identity.CredentialDiagnosticScope, Azure.Identity, Version=1.4.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8MemberType    : MethodModule        : Azure.Identity.dllStackTrace     :at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex)at Azure.Identity.ManagedIdentityCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)at Azure.Identity.ManagedIdentityCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)at Microsoft.Azure.PowerShell.Authenticators.MsalAccessTokenAcquirer.GetAccessTokenAsync(TokenCredential tokenCredential, TokenRequestContext requestContext, CancellationToken cancellationToken, String tenantId, String userId, String homeAccountId)at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(IAzureAccount account, IAzureEnvironment environment, String tenant, SecureString password, String promptBehavior, Action`1 promptAction, IAzureTokenCache tokenCache, String resourceId)at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.AcquireAccessToken(IAzureAccount account, IAzureEnvironment environment, String tenantId, SecureString password, String promptBehavior, Action`1 promptAction)at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.ListAccountTenants(IAzureAccount account, IAzureEnvironment environment, SecureString password, String promptBehavior, Action`1 promptAction)at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.Login(IAzureAccount account, IAzureEnvironment environment, String tenantId, String subscriptionId, String subscriptionName, SecureString password, Boolean skipValidation, Action`1 promptAction, String name, Boolean shouldPopulateContextList, Int32 maxContextPopulation)at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass111_2.<ExecuteCmdlet>b__4()at System.Threading.Tasks.Task`1.InnerInvoke()at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)--- End of stack trace from previous location where exception was thrown ---at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)--- End of stack trace from previous location where exception was thrown ---at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass111_0.<ExecuteCmdlet>b__1(AzureRmProfile localProfile, RMProfileClient profileClient, String name)at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass118_0.<SetContextWithOverwritePrompt>b__0(AzureRmProfile prof, RMProfileClient client)at Microsoft.Azure.Commands.Profile.Common.AzureContextModificationCmdlet.ModifyContext(Action`2 contextAction)at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.SetContextWithOverwritePrompt(Action`3 setContextAction)at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.ExecuteCmdlet()at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()Message        : ManagedIdentityCredential authentication failed: Service request failed.Status: 400 (Bad Request)Headers:Date: Wed, 10 Mar 2021 20:34:28 GMTContent-Length: 133InnerException :Type       : Azure.RequestFailedExceptionStatus     : 400TargetSite :Name          : MoveNextDeclaringType : Azure.Identity.ManagedIdentitySource+<HandleResponseAsync>d__9, Azure.Identity, Version=1.4.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8MemberType    : MethodModule        : Azure.Identity.dllStackTrace :at Azure.Identity.ManagedIdentitySource.HandleResponseAsync(Boolean async, TokenRequestContext context, Response response, CancellationToken cancellationToken)at Azure.Identity.ManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)at Azure.Identity.ManagedIdentityClient.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)at Azure.Identity.ManagedIdentityCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)Message    : Service request failed.Status: 400 (Bad Request)Headers:Date: Wed, 10 Mar 2021 20:34:28 GMTContent-Length: 133Source     : Azure.IdentityHResult    : -2146233088Source         : Azure.IdentityHResult        : -2146233088CategoryInfo          : CloseError: (:) [Connect-AzAccount], AuthenticationFailedExceptionFullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommandInvocationInfo        :MyCommand        : Connect-AzAccountScriptLineNumber : 16OffsetInLine     : 5HistoryId        : 1ScriptName       : C:\home\site\wwwroot\profile.ps1Line             :     Connect-AzAccount -IdentityPositionMessage  : At C:\home\site\wwwroot\profile.ps1:16 char:5+     Connect-AzAccount -Identity+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~PSScriptRoot     : C:\home\site\wwwrootPSCommandPath    : C:\home\site\wwwroot\profile.ps1InvocationName   : Connect-AzAccountCommandOrigin    : InternalScriptStackTrace      : at <ScriptBlock>, C:\home\site\wwwroot\profile.ps1: line 16PipelineIterationInfo :Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException : Result: ERROR: ManagedIdentityCredential authentication failed: Service request failed.Status: 400 (Bad Request)Headers:Date: Wed, 10 Mar 2021 20:34:28 GMTContent-Length: 133Exception             :Type           : Azure.Identity.AuthenticationFailedExceptionTargetSite     :Name          : FailWrapAndThrowDeclaringType : Azure.Identity.CredentialDiagnosticScope, Azure.Identity, Version=1.4.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8MemberType    : MethodModule        : Azure.Identity.dllStackTrace     :at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex)at Azure.Identity.ManagedIdentityCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)at Azure.Identity.ManagedIdentityCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)at Microsoft.Azure.PowerShell.Authenticators.MsalAccessTokenAcquirer.GetAccessTokenAsync(TokenCredential tokenCredential, TokenRequestContext requestContext, CancellationToken cancellationToken, String tenantId, String userId, String homeAccountId)at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(IAzureAccount account, IAzureEnvironment environment, String tenant, SecureString password, String promptBehavior, Action`1 promptAction, IAzureTokenCache tokenCache, String resourceId)at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.AcquireAccessToken(IAzureAccount account, IAzureEnvironment environment, String tenantId, SecureString password, String promptBehavior, Action`1 promptAction)at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.ListAccountTenants(IAzureAccount account, IAzureEnvironment environment, SecureString password, String promptBehavior, Action`1 promptAction)at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.Login(IAzureAccount account, IAzureEnvironment environment, String tenantId, String subscriptionId, String subscriptionName, SecureString password, Boolean skipValidation, Action`1 promptAction, String name, Boolean shouldPopulateContextList, Int32 maxContextPopulation)at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass111_2.<ExecuteCmdlet>b__4()at System.Threading.Tasks.Task`1.InnerInvoke()at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)--- End of stack trace from previous location where exception was thrown ---at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)--- End of stack trace from previous location where exception was thrown ---at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass111_0.<ExecuteCmdlet>b__1(AzureRmProfile localProfile, RMProfileClient profileClient, String name)at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass118_0.<SetContextWithOverwritePrompt>b__0(AzureRmProfile prof, RMProfileClient client)at Microsoft.Azure.Commands.Profile.Common.AzureContextModificationCmdlet.ModifyContext(Action`2 contextAction)at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.SetContextWithOverwritePrompt(Action`3 setContextAction)at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.ExecuteCmdlet()at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()Message        : ManagedIdentityCredential authentication failed: Service request failed.Status: 400 (Bad Request)Headers:Date: Wed, 10 Mar 2021 20:34:28 GMTContent-Length: 133InnerException :Type       : Azure.RequestFailedExceptionStatus     : 400TargetSite :Name          : MoveNextDeclaringType : Azure.Identity.ManagedIdentitySource+<HandleResponseAsync>d__9, Azure.Identity, Version=1.4.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8MemberType    : MethodModule        : Azure.Identity.dllStackTrace :at Azure.Identity.ManagedIdentitySource.HandleResponseAsync(Boolean async, TokenRequestContext context, Response response, CancellationToken cancellationToken)at Azure.Identity.ManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)at Azure.Identity.ManagedIdentityClient.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)at Azure.Identity.ManagedIdentityCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)Message    : Service request failed.Status: 400 (Bad Request)Headers:Date: Wed, 10 Mar 2021 20:34:28 GMTContent-Length: 133Source     : Azure.IdentityHResult    : -2146233088Source         : Azure.IdentityHResult        : -2146233088CategoryInfo          : CloseError: (:) [Connect-AzAccount], AuthenticationFailedExceptionFullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommandInvocationInfo        :MyCommand        : Connect-AzAccountScriptLineNumber : 16OffsetInLine     : 5HistoryId        : 1ScriptName       : C:\home\site\wwwroot\profile.ps1Line             :     Connect-AzAccount -IdentityPositionMessage  : At C:\home\site\wwwroot\profile.ps1:16 char:5+     Connect-AzAccount -Identity+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~PSScriptRoot     : C:\home\site\wwwrootPSCommandPath    : C:\home\site\wwwroot\profile.ps1InvocationName   : Connect-AzAccountCommandOrigin    : InternalScriptStackTrace      : at <ScriptBlock>, C:\home\site\wwwroot\profile.ps1: line 16PipelineIterationInfo :Exception: ManagedIdentityCredential authentication failed: Service request failed.Status: 400 (Bad Request)Headers:Date: Wed, 10 Mar 2021 20:34:28 GMTContent-Length: 133Stack:    at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex)at Azure.Identity.ManagedIdentityCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)at Azure.Identity.ManagedIdentityCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)at Microsoft.Azure.PowerShell.Authenticators.MsalAccessTokenAcquirer.GetAccessTokenAsync(TokenCredential tokenCredential, TokenRequestContext requestContext, CancellationToken cancellationToken, String tenantId, String userId, String homeAccountId)at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(IAzureAccount account, IAzureEnvironment environment, String tenant, SecureString password, String promptBehavior, Action`1 promptAction, IAzureTokenCache tokenCache, String resourceId)at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.AcquireAccessToken(IAzureAccount account, IAzureEnvironment environment, String tenantId, SecureString password, String promptBehavior, Action`1 promptAction)at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.ListAccountTenants(IAzureAccount account, IAzureEnvironment environment, SecureString password, String promptBehavior, Action`1 promptAction)at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.Login(IAzureAccount account, IAzureEnvironment environment, String tenantId, String subscriptionId, String subscriptionName, SecureString password, Boolean skipValidation, Action`1 promptAction, String name, Boolean shouldPopulateContextList, Int32 maxContextPopulation)at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass111_2.<ExecuteCmdlet>b__4()at System.Threading.Tasks.Task`1.InnerInvoke()at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)--- End of stack trace from previous location where exception was thrown ---at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)--- End of stack trace from previous location where exception was thrown ---at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass111_0.<ExecuteCmdlet>b__1(AzureRmProfile localProfile, RMProfileClient profileClient, String name)at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass118_0.<SetContextWithOverwritePrompt>b__0(AzureRmProfile prof, RMProfileClient client)at Microsoft.Azure.Commands.Profile.Common.AzureContextModificationCmdlet.ModifyContext(Action`2 contextAction)at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.SetContextWithOverwritePrompt(Action`3 setContextAction)at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.ExecuteCmdlet()at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
2021-03-10T20:34:30.678 [Error] Errors reported while executing profile.ps1. See logs for detailed errors. Profile location: C:\home\site\wwwroot\profile.ps1.
2021-03-10T20:34:34.580 [Error] ERROR: Run Connect-AzAccount to login.Exception             :Type        : System.Management.Automation.PSInvalidOperationExceptionErrorRecord :Exception             :Type    : System.Management.Automation.ParentContainsErrorRecordExceptionMessage : Run Connect-AzAccount to login.HResult : -2146233087CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordExceptionFullyQualifiedErrorId : InvalidOperationTargetSite  :Name          : HandleExceptionDeclaringType : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBaseMemberType    : MethodModule        : Microsoft.Azure.PowerShell.Cmdlets.ResourceManager.dllStackTrace  :at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.HandleException(ExceptionDispatchInfo capturedException)at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.ExecuteCmdlet()at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()Message     : Run Connect-AzAccount to login.Source      : Microsoft.Azure.PowerShell.Cmdlets.ResourceManagerHResult     : -2146233079CategoryInfo          : CloseError: (:) [Get-AzResourceGroup], PSInvalidOperationExceptionFullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceGroupCmdletInvocationInfo        :MyCommand        : Get-AzResourceGroupScriptLineNumber : 7OffsetInLine     : 28HistoryId        : 1ScriptName       : C:\home\site\wwwroot\func-UserIdenityTest\run.ps1Line             : $nonprodRespourceGroups = (Get-AzResourceGroup -Tag @{'ApmID' = 'XXXXXX' })PositionMessage  : At C:\home\site\wwwroot\func-UserIdenityTest\run.ps1:7 char:28+ … odRespourceGroups = (Get-AzResourceGroup -Tag @{'ApmID' = 'XXXXXX' })+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~PSScriptRoot     : C:\home\site\wwwroot\func-UserIdenityTestPSCommandPath    : C:\home\site\wwwroot\func-UserIdenityTest\run.ps1InvocationName   : Get-AzResourceGroupCommandOrigin    : InternalScriptStackTrace      : at <ScriptBlock>, C:\home\site\wwwroot\func-UserIdenityTest\run.ps1: line 7PipelineIterationInfo :Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException : Result: ERROR: Run Connect-AzAccount to login.Exception             :Type        : System.Management.Automation.PSInvalidOperationExceptionErrorRecord :Exception             :Type    : System.Management.Automation.ParentContainsErrorRecordExceptionMessage : Run Connect-AzAccount to login.HResult : -2146233087CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordExceptionFullyQualifiedErrorId : InvalidOperationTargetSite  :Name          : HandleExceptionDeclaringType : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBaseMemberType    : MethodModule        : Microsoft.Azure.PowerShell.Cmdlets.ResourceManager.dllStackTrace  :at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.HandleException(ExceptionDispatchInfo capturedException)at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.ExecuteCmdlet()at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()Message     : Run Connect-AzAccount to login.Source      : Microsoft.Azure.PowerShell.Cmdlets.ResourceManagerHResult     : -2146233079CategoryInfo          : CloseError: (:) [Get-AzResourceGroup], PSInvalidOperationExceptionFullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceGroupCmdletInvocationInfo        :MyCommand        : Get-AzResourceGroupScriptLineNumber : 7OffsetInLine     : 28HistoryId        : 1ScriptName       : C:\home\site\wwwroot\func-UserIdenityTest\run.ps1Line             : $nonprodRespourceGroups = (Get-AzResourceGroup -Tag @{'ApmID' = 'XXXXXX' })PositionMessage  : At C:\home\site\wwwroot\func-UserIdenityTest\run.ps1:7 char:28+ … odRespourceGroups = (Get-AzResourceGroup -Tag @{'ApmID' = 'XXXXXX' })+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~PSScriptRoot     : C:\home\site\wwwroot\func-UserIdenityTestPSCommandPath    : C:\home\site\wwwroot\func-UserIdenityTest\run.ps1InvocationName   : Get-AzResourceGroupCommandOrigin    : InternalScriptStackTrace      : at <ScriptBlock>, C:\home\site\wwwroot\func-UserIdenityTest\run.ps1: line 7PipelineIterationInfo :Exception: Run Connect-AzAccount to login.Stack:    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.HandleException(ExceptionDispatchInfo capturedException)at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.ExecuteCmdlet()at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
2021-03-10T20:34:34.958 [Information] INFORMATION: PowerShell HTTP trigger function processed a request. +
2021-03-10T20:34:35.082 [Information] Executed 'Functions.func-UserIdenityTest' (Succeeded, Id=da3303b3-d3bd-453d-bd93-05e5ace13cee, Duration=14965ms)

**Comment by v-anvari** [comment]
Hi @narenkv , Thank you for the feedback, After having a look through some more related issues, I came across this [similar report](https://github.com/Azure/azure-sdk-for-net/issues/11400#issuecomment-620179175).

Which mentions you need to set Environment Variable AZURE_CLIENT_ID to be the User assigned MSI's client ID

If you want to do this through the Azure portal.
You can head over to your Azure App Service -> Settings | Configuration -> Application Settings
Add or update the AZURE_CLIENT_ID app setting to the User assigned MSI's client ID.

**Comment by v-anvari** [comment]
Let us know if the solution helps, closing this issue as the required information is provided, please feel free to reach back to us in case of any further queries related to this issue

**Comment by rachaelsingleton** [comment]
I'm getting the same error with a system assigned managed identity.
