### ISSUE TITLE
Cannot be installed on latest VS2019

### ISSUE THREAD

**Issue by kgflying** [Azure/Azure-Functions#1884]
1. Install latest VS2019, 16.9.4
2. Download the plugin from https://marketplace.visualstudio.com/items?itemName=VisualStudioWebandAzureTools.AzureFunctionsandWebJobsTools.
3. Install it.

Observed:
![image](https://user-images.githubusercontent.com/12282281/114898449-f2f28e80-9dc6-11eb-98db-9d7881d0e431.png)

**Comment by 9527KGG** [comment]
Log
...
4/15/2021 08:48:12 - Searching for applicable products...
4/15/2021 08:48:12 - Found installed product - Global Location
4/15/2021 08:48:12 - Found installed product - Visual Studio Enterprise 2019
4/15/2021 08:48:12 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by o-k-a-y** [comment]
Maybe that's why I can't get my function to run. I'm also unable to find the extension to install.

**Comment by v-bbalaiagar** [comment]
Hi @kgflying, Thank you for reaching out to us, checking internally on this issue

**Comment by v-bbalaiagar** [comment]
Hi @kgflying, If you look at the marketplace it targets visual studio 2017 only. You just need to ensure the options, the cloud workloads are selected when you install visual studio, so the extension comes with visual studio building. But there is no need to install the plugins separately, that only targets visual studio 2017 when the set of extensions pre-installed.

**Comment by kgflying** [comment]
I see. Thanks for letting me know

**Comment by v-bbalaiagar** [comment]
Hi @kgflying, Closing this issue as the required information is provided, please feel free to reach back to us in case of any further queries related to this issue
