### ISSUE TITLE
Visual Studio 2022 Azure Functions error Error MSB4018 The "GenerateFunctionsExtensionsMetadata" task failed unexpectedly

### ISSUE THREAD

**Issue by vijayrkn** [Azure/Azure-Functions#2125]
Function App name:
Tools used:
New V4 app or existing V3 app migrated to V4:

Creating the bug on behalf of the VS customer: https://developercommunity.visualstudio.com/t/Visual-Studio-2022-Azure-Functions-error/1609727

```
Severity Code Description Project File Line Suppression State
Error MSB4018 The “GenerateFunctionsExtensionsMetadata” task failed unexpectedly.
System.ComponentModel.Win32Exception (0x80004005): Access is denied

Server stack trace:
at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
at ExtensionsMetadataGenerator.BuildTasks.GenerateFunctionsExtensionsMetadata.Execute()
at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]:
at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
at Microsoft.Build.Framework.ITask.Execute()
at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() GettingStartedVisualStudio C:\Users\ATwigg.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\4.0.1\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets 37

When i set the MSBuild verbosity to diagnostic i get…

1>Target “_GenerateFunctionsExtensionsMetadataPostBuild” in file “C:\Users\ATwigg.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\4.0.1\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets”:
1> Using “GenerateFunctionsExtensionsMetadata” task from assembly “C:\Users\ATwigg.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\4.0.1\build…\tools\net46\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.dll”.
1> Task “GenerateFunctionsExtensionsMetadata”
1> Task Parameter:OutputPath=C:\Users\ATwigg\dotnet-learning\azure-functions\GettingStartedVisualStudio\GettingStartedVisualStudio\bin\Debug\net6.0\bin
1> Task Parameter:SourcePath=C:\Users\ATwigg\dotnet-learning\azure-functions\GettingStartedVisualStudio\GettingStartedVisualStudio\bin\Debug\net6.0\bin
1> Extensions generator working directory: ‘C:\Users\ATwigg.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\4.0.1\tools\net46…\netstandard2.0\generator’
1> Extensions generator path: ‘dotnet’
1> Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.Console.dll “C:\Users\ATwigg\dotnet-learning\azure-functions\GettingStartedVisualStudio\GettingStartedVisualStudio\bin\Debug\net6.0\bin” “C:\Users\ATwigg\dotnet-learning\azure-functions\GettingStartedVisualStudio\GettingStartedVisualStudio\bin\Debug\net6.0\bin\extensions.json”
1> C:\Users\ATwigg.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\4.0.1\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(37,5): error MSB4018: The “GenerateFunctionsExtensionsMetadata” task failed unexpectedly.
1> C:\Users\ATwigg.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\4.0.1\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(37,5): error MSB4018: System.ComponentModel.Win32Exception (0x80004005): Access is denied
1> C:\Users\ATwigg.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\4.0.1\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(37,5): error MSB4018:
1> C:\Users\ATwigg.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\4.0.1\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(37,5): error MSB4018: Server stack trace:
1> C:\Users\ATwigg.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\4.0.1\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(37,5): error MSB4018: at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
1> C:\Users\ATwigg.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\4.0.1\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(37,5): error MSB4018: at ExtensionsMetadataGenerator.BuildTasks.GenerateFunctionsExtensionsMetadata.Execute()
1> C:\Users\ATwigg.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\4.0.1\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(37,5): error MSB4018: at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
1> C:\Users\ATwigg.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\4.0.1\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(37,5): error MSB4018: at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
1> C:\Users\ATwigg.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\4.0.1\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(37,5): error MSB4018:
1> C:\Users\ATwigg.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\4.0.1\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(37,5): error MSB4018: Exception rethrown at [0]:
1> C:\Users\ATwigg.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\4.0.1\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(37,5): error MSB4018: at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
1> C:\Users\ATwigg.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\4.0.1\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(37,5): error MSB4018: at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
1> C:\Users\ATwigg.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\4.0.1\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(37,5): error MSB4018: at Microsoft.Build.Framework.ITask.Execute()
1> C:\Users\ATwigg.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\4.0.1\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(37,5): error MSB4018: at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1> C:\Users\ATwigg.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\4.0.1\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(37,5): error MSB4018: at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
1> Done executing task “GenerateFunctionsExtensionsMetadata” – FAILED.
1>Done building target “_GenerateFunctionsExtensionsMetadataPostBuild” in project “GettingStartedVisualStudio.csproj” – FAILED.
1>
1>Done building project “GettingStartedVisualStudio.csproj” – FAILED.
```

**Comment by andrew-twigg** [comment]
Hi, yes this is a new V4 app. I raised the original issue, and i get the errors when i install Visual Studio 2022 and then follow the [quick-start](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-your-first-function-visual-studio). Since raising the error I looked a bit deeper and i think the error is coming from [this point](https://github.com/Azure/azure-functions-host/blob/6c9e9aa9411370bc6fd3972c40ee834a8339346a/tools/ExtensionsMetadataGenerator/src/ExtensionsMetadataGenerator/BuildTasks/GenerateFunctionsExtensionsMetadata.cs#L52) in ExtensionsMetadataGenerator.

I see it's creating a new process and the error is access denied. I am running Visual Studio as administrator. Not sure if it's some policy on my work laptop that's preventing this from running. I have got it working on a different machine.

The VS 2022 install is next to a VS 2019 install. I tried uninstalling 2019 with no luck.

**Comment by v-bbalaiagar** [comment]
Hi @andrew-twigg , Apologies for the delayed response, We would like to know if you are still facing the same issue so that I can route this issue to concerned team.

**Comment by andrew-twigg** [comment]
Hi, yes still experiencing the issue.

Thanks

**Comment by SogoGolf** [comment]
I just got this same error also ; Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.1.6

**Comment by praveshpesswani** [comment]
@vijayrkn - Do we have any solution for this issue?
