### ISSUE TITLE
Running Azure function locally fails on MacOS

### ISSUE THREAD

**Issue by sanzgiri** [Azure/Azure-Functions#2130]
I am following the instructions here on getting started with Azure Functions, using VS Code on MacOS Big Sur (11.6.2)
https://docs.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-python

The local deployment fails with the following errors:

```
[2021-12-21T00:12:34.777Z] Traceback (most recent call last):
[2021-12-21T00:12:34.777Z]   File "/usr/local/Cellar/azure-functions-core-tools@4/4.0.3971/workers/python/3.9/OSX/X64/azure_functions_worker/bindings/shared_memory_data_transfer/file_accessor_unix.py", line 127, in _get_valid_mem_map_dirs
[2021-12-21T00:12:34.777Z]     os.makedirs(dir_path)
[2021-12-21T00:12:34.777Z]   File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 215, in makedirs
[2021-12-21T00:12:34.777Z]     makedirs(head, exist_ok=exist_ok)
[2021-12-21T00:12:34.778Z]   File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 225, in makedirs
[2021-12-21T00:12:34.778Z]     mkdir(name, mode)
[2021-12-21T00:12:34.778Z] PermissionError: [Errno 1] Operation not permitted: '/dev/shm'
```

**Comment by v-bbalaiagar** [comment]
Hi @sanzgiri, Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by v-bbalaiagar** [comment]
Hi @sanzgiri , We have reproduced the same from our end following the same Document and found everything was working well. You need to navigate to the highlighted URL mentioned in the below image which you will be finding in the console, in order to check if Azure functions are working. 

![image](https://user-images.githubusercontent.com/74654421/148347450-4e42555f-d7c4-49fe-ac66-81a5a3fbe966.png)

The errors that you were mentioning in the question are the tracebacks which you will be receiving while running Azure Functions.

![image](https://user-images.githubusercontent.com/74654421/148347630-b89b22e3-5244-497f-99a8-2ce6df82927d.png)

Here is the output:

![image](https://user-images.githubusercontent.com/74654421/148347741-d3b9f257-e0e7-4366-924e-74d8adb387f5.png)

**Comment by sanzgiri** [comment]
Thanks, @v-bbalaiagar! Confirmed this is working.
