### ISSUE TITLE
can't add CancellationToken to HTTP triggered functions

### ISSUE THREAD

**Issue by mizrael** [Azure/Azure-Functions#2135]
Seems that it's not possible to add a CancellationToken to Http-triggered functions in isolated mode.

In VS2022, I created a .NET6 isolated function app, with an HTTP trigger, and updated the function signature from this:

```csharp
public HttpResponseData Run([HttpTrigger(AuthorizationLevel.Function, "get", "post")] HttpRequestData req)
```

to this:

```csharp
public HttpResponseData Run([HttpTrigger(AuthorizationLevel.Function, "get", "post")] HttpRequestData req, CancellationToken cancellationToken = default)
```

this is the error I get:

```
[2021-12-26T21:46:35.479Z] Executing 'Functions.Function1' (Reason='This function was programmatically called via the host APIs.', Id=9dfc45a9-94d0-43d6-a17d-906c1aef945a)
[2021-12-26T21:46:35.739Z] Executed 'Functions.Function1' (Failed, Id=9dfc45a9-94d0-43d6-a17d-906c1aef945a, Duration=295ms)
[2021-12-26T21:46:35.741Z] System.Private.CoreLib: Exception while executing function: Functions.Function1. System.Private.CoreLib: Result: Failure
Exception: System.NullReferenceException: Object reference not set to an instance of an object.
[2021-12-26T21:46:35.742Z]    at lambda_method1(Closure , Function1 , Object[] )
[2021-12-26T21:46:35.743Z]    at Microsoft.Azure.Functions.Worker.Invocation.MethodInvokerWithReturnValue`2.InvokeAsync(TReflected instance, Object[] arguments) in D:\a\1\s\src\DotNetWorker.Core\Invocation\MethodInvokerWithReturnValue.cs:line 22
[2021-12-26T21:46:35.745Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 31
[2021-12-26T21:46:35.747Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 37
[2021-12-26T21:46:35.750Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2021-12-26T21:46:35.756Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 166
Stack:    at lambda_method1(Closure , Function1 , Object[] )
[2021-12-26T21:46:35.761Z]    at Microsoft.Azure.Functions.Worker.Invocation.MethodInvokerWithReturnValue`2.InvokeAsync(TReflected instance, Object[] arguments) in D:\a\1\s\src\DotNetWorker.Core\Invocation\MethodInvokerWithReturnValue.cs:line 22
[2021-12-26T21:46:35.763Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 31
[2021-12-26T21:46:35.765Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 37
[2021-12-26T21:46:35.767Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2021-12-26T21:46:35.769Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 166.

```

The same change in a "standard", non-isolated function app, works fine.

**Comment by v-bbalaiagar** [comment]
Hi @pragnagopa / @fabiocav , Could you please look into this issue.

**Comment by mizrael** [comment]
@v-bbalaiagar / @pragnagopa / @fabiocav  any update on this?

**Comment by ptjuanramos** [comment]
@mizrael This only happens with v4?

**Comment by mizrael** [comment]
@ptjuanramos just tried with a v3 non-isolated funcapp, works fine there.

**Comment by ptjuanramos** [comment]
@mizrael Thanks! For isolated host, I saw one time a problem related with this

**Comment by v-bbalaiagar** [comment]
This issue is relating to an issue which is already being tracked and the updates will be given there - https://github.com/Azure/azure-functions-dotnet-worker/issues/180

Closing this issue here. Please find the space for further updates.
