### ISSUE TITLE
"409 The specified container already exists." 

### ISSUE THREAD

**Issue by tymtam2** [Azure/Azure-Functions#2166]
In my Azure Function which doesn't have any storage account code I'm getting the following warning in Application Insights.

```
Error response [15fd74...ec3601] 409 The specified container already exists. (00.0s)
Server:Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id:b72b1...f5-26564f000000
x-ms-client-request-id:15fd74...0ec3601
x-ms-version:2020-08-04
x-ms-error-code:ContainerAlreadyExists
Date:Mon, 21 Feb 2022 07:33:56 GMT
Content-Length:230
Content-Type:application/xml
```

I think it's reasonable to assume this is something to do with the storage account that the Azure Functions use to record their state etc.

SDK version	azurefunctions: 4.1.3.17473

Is there a way to debug and/or resolve the issue?

**Comment by domasd** [comment]
We are experiencing the same issue on some of our v4 functions. 

From what we investigated it appears that this warning (or similar one `404 The specified container does not exist.`) are being spit by function sdk, but in the same time, by default, they are supressed and if you have default `host.json` in place, you shouldn't see them.

Our assumption is that we are seeing these warnings because we override default log level.
So currently we are just filtering the category `Azure.Core` with `Error` severity and it fixes the issue.

Just for reference, our `host.json` looks like this:
```
{
  "version": "2.0",
  "logging": {
    "logLevel": {
      "default": "Warning",
      "Custom": "Information",
      "Function": "Information", // dependency telemetry, used to analyzing dependencies and their performance
      "Host.Results": "Information", // request telemetry, used for analyzing execution performance
      "Azure.Core":  "Error" // suppressing sdk blob warnings 
    }
  }
}

```

**Comment by tymtam2** [comment]
I'm not sure if this is relevant but all my v4 function apps complain that "Storage is not configured correctly", but they all work. 

![image](https://user-images.githubusercontent.com/1097613/155478164-ae45c291-42a3-4137-b19e-d37ac20d7c02.png)

**Comment by v-bbalaiagar** [comment]
Hi @pragnagopa , Could you please look into this issue

**Comment by pragnagopa** [comment]
Tagging @AnatoliB @gzuber for triage

**Comment by tymtam2** [comment]
Just adding more info. The problem seem to be coming in batches of 4 issues: 

```
Error response [06ac509e-...] 409 The specified container already exists. (00.1s)
Server:Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id:e483b8d7-...
x-ms-client-request-id:06ac509e-...
x-ms-version:2020-08-04
x-ms-error-code:ContainerAlreadyExists
Date:Tue, 01 Mar 2022 07:11:44 GMT
Content-Length:230
Content-Type:application/xml

Error response [4c57b299-...] 404 The specified blob does not exist. (00.0s)
Server:Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id:80603de1-...
x-ms-client-request-id:4c57b299-...
x-ms-version:2020-10-02
x-ms-error-code:BlobNotFound
Date:Tue, 01 Mar 2022 07:11:14 GMT
Content-Length:215
Content-Type:application/xml

Error response [9d09446f-...] 404 The specified blob does not exist. (00.0s)
Transfer-Encoding:chunked
Server:Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id:80603da6-...
x-ms-client-request-id:9d09446f-...
x-ms-version:2020-10-02
x-ms-error-code:BlobNotFound
Date:Tue, 01 Mar 2022 07:11:14 GMT

Error response [b873e541-...] 409 The specified container already exists. (00.3s)
Server:Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id:80603cc6-...
x-ms-client-request-id:b873e541-...
x-ms-version:2020-10-02
x-ms-error-code:ContainerAlreadyExists
Date:Tue, 01 Mar 2022 07:11:13 GMT
Content-Length:230
Content-Type:application/xml
```

**Comment by AnatoliB** [comment]
I think Application Insights is just a messenger here. Something in the host process is trying to access a blob, and this attempt is captured, but I don't see any indication that this blob is accessed _because_ of Application Insights.

Does this repro with the simplest "hello world" app with a single HTTP trigger?

**Comment by tymtam2** [comment]
Category for these isssues is `Azure.Core.1`.

As I was setting up trying the out-of-the-box http trigger function  I realised that this issue is only reported by the functions with [EventHubTrigger]. I can see now that the functions that only have a http trigger do not report these 4 issues.

**Comment by AnatoliB** [comment]
@tymtam2 Do you know which version of the Event Hubs extension you are using?

**Comment by tymtam2** [comment]
Here are all the referenced packages
```
<PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.0.123" />
    <PackageReference Include="Microsoft.ApplicationInsights" Version="2.20.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.EventHubs" Version="5.0.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="6.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.1.0" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.406">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Data.SqlClient" Version="4.8.3" />
  </ItemGroup>
```

I get the 4 issues when running locally (not just when deployed) and in the bin folder the version of 
Azure.Messaging.EventHubs.dll is 5.6.2
and Microsoft.Azure.WebJobs.Extensions.EventHubs.dll is 5.0.0.


As an experiment I added an explicit dependency on Azure.Messaging.EventHubs 5.7.0-beta.3 but after doing that the function reports on startup: 
`Microsoft.Azure.WebJobs.Host: Error indexing method '(name_here)'. Microsoft.Azure.WebJobs.Host: Multiple properties named 'ContentType' found in type 'EventData'.`.

**Comment by AnatoliB** [comment]
@alrod Track2 extension issue?

**Comment by alrod** [comment]
@tymtam2, 
can you please try to use "Microsoft.Azure.WebJobs.Extensions.EventHubs" Version="4.3.1"? 
do you see the "409 The specified container already exists." in this case?

**Comment by tymtam2** [comment]
I've tried "Microsoft.Azure.WebJobs.Extensions.EventHubs" Version="4.3.1" and I don't see the warnings.

**Comment by GuiGimenez** [comment]
This occurs with [ServiceBusTrigger] as well

**Comment by jawinnerjr** [comment]
Any resolution on this.  Using VS 2022 MAC RC2 om M1. Worked fine until Microsoft.Azure.Webjobs.Extensions.EventHubs updated to 5.1.0.  Rolling back however does not resolve the issue. This is specifically an issue with the event hub trigger in Azure functions ~4 / .NET 6. 

[2022-05-12T17:32:08.551Z] Microsoft.Azure.WebJobs.Host: Error indexing method '<FunctionName>'. Microsoft.Azure.WebJobs.Host: Multiple properties named 'ContentType' found in type 'EventData'.
[2022-05-12T17:32:08.600Z] Error indexing method '<FunctionName>'
[2022-05-12T17:32:08.600Z] Microsoft.Azure.WebJobs.Host: Error indexing method '<FunctionName>'. Microsoft.Azure.WebJobs.Host: Multiple properties named 'ContentType' found in type 'EventData'.
[2022-05-12T17:32:08.601Z] Function '<FunctionName>' failed indexing and will be disabled.

When deployed to Azure the functions load and execute properly. This issue appears to be limited to the Visual Studio environment only.

**Comment by wkoeter** [comment]
I'm also seeing this warning when [TimerTrigger] on .NET 6 with dotnet-isolated.

```
[2022-05-25T10:17:21.413Z] Error response [26c59ccf-e824-4fb0-a586-9cd340504cba] 409 The specified container already exists. (00.0s)
[2022-05-25T10:17:21.417Z] Server:Azurite-Blob/3.14.1
[2022-05-25T10:17:21.419Z] x-ms-error-code:ContainerAlreadyExists
[2022-05-25T10:17:21.420Z] x-ms-request-id:277e9701-a041-4f85-802d-234f3d0c8caa
[2022-05-25T10:17:21.421Z] Date:Wed, 25 May 2022 10:17:21 GMT
[2022-05-25T10:17:21.423Z] Connection:keep-alive
[2022-05-25T10:17:21.424Z] Keep-Alive:REDACTED
[2022-05-25T10:17:21.426Z] Transfer-Encoding:chunked
[2022-05-25T10:17:21.427Z] Content-Type:application/xml
```

Seems to me like the Core is trying to do a CreateIfNotExists somewhere internally or something because TimerTrigger functions using blob storage, and that is shown in our logs.

The timers run fine by the way.

**Comment by michaeldaw** [comment]
No doubt a manifestation of this issue,  which hasn't been fixed for 10 years 😖
[Container.CreateIfNotExist throws exception if container exists](https://github.com/Azure/azure-sdk-for-net/issues/109#issuecomment-1118217363)

If anyone gets assigned to this (and I hope someone does), make sure to check if the container exists before trying to create it. CreateIfNotExist throws an exception if the container exists. If that sounds absurd, it's because it is.

**Comment by klenium** [comment]
I'm getting this error after upgrading a project/host from .NET Core 3.1 / AF 3 to .NET 6 / AF 4. I'm not using any event* triggers, only http/timer/durableTask.

**Comment by brennfoster** [comment]
I just realized that I was not awaiting the host.RunAsync() command in Program.cs and that's why this was failing for me.

**Comment by xsurfer** [comment]
is there any update on this issue? I am facing the same issue while using net6 and function app v4. Thanks

**Comment by SaveliyKolesnikov** [comment]
This occurs with [ServiceBusTrigger] after upgrading from .NET Core 3.1 / AF 3 to .NET 6 / AF 4.

**Comment by jameswoodley** [comment]
I am seeing this behavior with [ServiceBusTrigger] and [TimerTrigger]

**Comment by luisgmgouveia** [comment]
> _Our assumption is that we are seeing these warnings because we override default log level._ (@domasd)

I would just like to say that @domasd assumption seems absolutely correct. My application is in production for 6 months and I've never came across this warning before I customized my host.json. Once I've changed the loglevel, I've started seeing this warning.

**Comment by MSIT-BPSC-IOT** [comment]
Does this require any code changes? Even with below values in host.json (V4 function), the issue still persists

{
  "version": "2.0",
  "functionTimeout": "00:55:00",
  "logging": {
    "logLevel": {
      "default": "Warning",
      "Custom": "Information",
      "Function": "Information",
      "Host.Results": "Information",
      "Azure.Core": "Error",
      "Azure.Messaging.ServiceBus": "Error",
      "Azure.Storage.Blobs": "Error",
      "Microsoft.Azure.WebJobs.Extensions.Storage": "Error",
      "Microsoft.Azure.WebJobs.Extensions.ServiceBus": "Error"
    }
  }
}

**Comment by xlight05** [comment]
Getting the same issue for http trigger in prod.  For some reason, only in Linux. Works just fine in windows.
host json 
```json
{
  "version": "2.0",
  "extensions": {
    "http": {
      "routePrefix": ""
    }
  },
  "customHandler": {
    "description": {
      "defaultExecutablePath": "java",
      "defaultWorkerPath": "multi_out.jar",
      "arguments": [
        "-jar"
      ]
    },
    "enableForwardingHttpRequest": false
  },
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[3.*, 4.0.0)"
  }
}
```

@pragnagopa @alrod

**Comment by hhao01-becls** [comment]
If you use Serilog as the logging provider, you can add the following app setting to ignore the warning logs.
```JSON
{
  "Serilog": {
    "MinimumLevel": {
      "Override": {
        "Azure.Core": "Error"
      }
    }
  }
}
```
But the countermeasure will ignore other warnings.

**Comment by jaschrep-msft** [comment]
This looks to be the same issue as tracked here https://github.com/Azure/azure-sdk-for-net/issues/21511

**Comment by MarGraz** [comment]
Same problem here, I'm using **.net 6** and **Azure Function v. 4**.

Those are the **dependencies** in my project:

```
    <PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.2.2" />
    <PackageReference Include="Azure.Identity" Version="1.8.2" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="5.1.2" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.2.0" />
```

The **exception** seems to be called by:   
```
BlobContainerClient.CreateIfNotExists ---> BlobContainerClient.Create
```

**it seems to happen in my implementation when I use**:
```
await blobContainerClient.CreateIfNotExistsAsync(PublicAccessType.BlobContainer);
```
I see this **error in Azure Application Insights**:

```
Azure.RequestFailedException: The specified container already exists.
RequestId:7aadc04c-601e-0051-2726-7fab43000000
Time:2023-05-05T07:54:33.5483399Z
Status: 409 (The specified container already exists.)
ErrorCode: ContainerAlreadyExists

Content:
﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.
RequestId:7aadc04c-601e-0051-2726-7fab43000000
Time:2023-05-05T07:54:33.5483399Z</Message></Error>

Headers:
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 7aadc04c-601e-0051-2726-7fab43000000
x-ms-client-request-id: 45bb8263-7256-4297-9f81-12c74c6ecb1d
x-ms-version: 2022-11-02
x-ms-error-code: ContainerAlreadyExists
Date: Fri, 05 May 2023 07:54:32 GMT
Content-Length: 230
Content-Type: application/xml

   at Azure.Storage.Blobs.ContainerRestClient.Create(Nullable`1 timeout, IDictionary`2 metadata, Nullable`1 access, String defaultEncryptionScope, Nullable`1 preventEncryptionScopeOverride, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobContainerClient.CreateInternal(PublicAccessType publicAccessType, IDictionary`2 metadata, BlobContainerEncryptionScopeOptions encryptionScopeOptions, Boolean async, CancellationToken cancellationToken, String operationName)
```

Do you know if it is available a fix?

Thank you

**Comment by MarGraz** [comment]
I found [this conversation on stackoverflow](https://stackoverflow.com/questions/48893519/azure-table-storage-exception-409-conflict-unexpected) that seems interesting.

**Comment by c0rn3liusha11** [comment]
While suppressing the logging of this by only letting Error level messages through from Azure.Core works, it also means that any other actually valid warning messages will get missed.
It seems like the AZF SDK should be updated to change these messages to "Info" or "Debug" level if they are actually not actionable.

**Comment by MarGraz** [comment]
@c0rn3liusha11 thank you for your reply, I prefer to avoid suppress the log messages. I opened a [new issue here](https://github.com/Azure/Azure-Functions/issues/2370) and MS is checking the problem.

**Comment by mtrmmsoftware** [comment]
Having the same issue even if the `"Azure.Core": "Error" ` is set in the host.json, using the `Microsoft.Azure.Functions.Worker.Extensions.Storage` nuget package with version `6.2.0`

Any update on this issue?

**Comment by restfulhead** [comment]
Seems like we're now impacted by this since January 18. Now we have hundreds of these warning messages in our log. Suppressing warnings can't be the real solution.

Environment details
- Azure Function Runtime: `~4` (Node.js)
- Environment: Windows

```
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[3.3.0, 4.0.0)"
  },
```

**Comment by jasonvangundy** [comment]
This just started happening to me and my team as well.  We have deployed many nodejs function apps over the last year and we've never seen this. The one I am working on locally right now (as of yesterday) just started to have this issue.  Happens using Azurite and a real Azure storage account.

Environment details

- Nodejs 
- Environment: VSCode on Mac M1

```
Azure Functions Core Tools
Core Tools Version:       4.0.5455 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.27.5.21554
```

**Comment by phazlett** [comment]
This is also a problem for me, but only for HTTP triggered functions.

**Comment by drilko** [comment]
Hi, I'm getting thousands of these logs as well. Any update?

**Comment by scottcollins** [comment]
Is there any resolution to this yet?  I am using .net 8 isolated process and I am seeing it with [TimerTrigger]?

**Comment by Purgator** [comment]
I have the exact same problem with TimeTrigger.

**Comment by yarmoliq** [comment]
Same

**Comment by NicolaiSattler** [comment]
Still an issue for TimeTrigger and QueueTrigger.

**Comment by mirekkukla** [comment]
We're on .net9 isolated process and likewise still seeing it with `[TimerTrigger]`

**Comment by tdinckaya** [comment]
same issue,

error: ErrorMiddleware: Set HTTP body: "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>ContainerAlreadyExists</Code>\n  <Message>The specified container already exists.\nRequestId:4a70e3f1-697a-468f-8fa9-d4e77b128151\nTime:2025-01-07T14:19:15.507Z</Message>\n</Error>"
2025-01-07T19:06:29.822Z ae04eae3-2f53-4ce9-9a1e-b99df8107f6a error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2025-01-07T19:06:29.822Z ae04eae3-2f53-4ce9-9a1e-b99df8107f6a error: ErrorMiddleware: ErrorName=StorageError ErrorMessage="The table specified already exists."  ErrorHTTPStatusCode=409 ErrorHTTPStatusMessage=undefined ErrorHTTPHeaders={"x-ms-error-code":"TableAlreadyExists","x-ms-request-id":"ae04eae3-2f53-4ce9-9a1e-b99df8107f6a","x-ms-version":"2025-01-05"} ErrorHTTPBody="{\"odata.error\":{\"code\":\"TableAlreadyExists\",\"message\":{\"lang\":\"en-US\",\"value\":\"The table specified already exists.\\nRequestId:ae04eae3-2f53-4ce9-9a1e-b99df8107f6a\\nTime:2025-01-07T19:06:29.820Z\"}}}" ErrorStack="\"StorageError: The table specified already exists.\\n    at Function.getTableAlreadyExists (/root/.nvm/versions/node/v16.20.2/lib/node_modules/azurite/dist/src/table/errors/StorageErrorFactory.js:27:16)\\n    at LokiTableMetadataStore.checkIfTableExists (/root/.nvm/versions/node/v16.20.2/lib/node_modules/azurite/dist/src/table/persistence/LokiTableMetadataStore.js:554:49)\\n    at LokiTableMetadataStore.createTable (/root/.nvm/versions/node/v16.20.2/lib/node_modules/azurite/dist/src/table/persistence/LokiTableMetadataStore.js:97:14)\\n    at TableHandler.create (/root/.nvm/versions/node/v16.20.2/lib/node_modules/azurite/dist/src/table/handlers/TableHandler.js:40:34)\\n    at /root/.nvm/versions/node/v16.20.2/lib/node_modules/azurite/dist/src/table/generated/middleware/HandlerMiddlewareFactory.js:58:18\\n    at /root/.nvm/versions/node/v16.20.2/lib/node_modules/azurite/dist/src/table/generated/ExpressMiddlewareFactory.js:77:63\\n    at Layer.handle [as handle_request] (/root/.nvm/versions/node/v16.20.2/lib/node_modules/azurite/node_modules/express/lib/router/layer.js:95:5)\\n    at trim_prefix (/root/.nvm/versions/node/v16.20.2/lib/node_modules/azurite/node_modules/express/lib/router/index.js:328:13)\\n    at /root/.nvm/versions/node/v16.20.2/lib/node_modules/azurite/node_modules/express/lib/router/index.js:286:9\\n    at Function.process_params (/root/.nvm/versions/node/v16.20.2/lib/node_modules/azurite/node_modules/express/lib/router/index.js:346:12)\""

**Comment by MaxMommersteeg** [comment]
We're experiencing the same issue and it is flooding our logs.

We've put all our own tables and containers in bicep, so that we don't require a `CreateIfNotExistsAsync` from our code and can just assume that the table or container is available. This already prevents from making unnecessary dependency calls to the storage account for performing the check.

However, the issues that remain can't be resolved from our end and suppressing logs is far from ideal imho. Eagerly waiting for a response / workaround / fix.

**Comment by sherman89** [comment]
Same issue here.

Don't hold your breath and just set `"Azure.Core": "Error"`, this might not get fixed for years to come.

**Comment by guard-csk** [comment]
Still seeing this in September 2026:

Functions host: 4.1053.200.26403
Microsoft.Azure.Functions.Worker: 2.52.0
Timer extension: 4.3.1
Storage Queues extension: 5.5.4

We started seeing recurring Azure.Core warnings in Application Insights after adding queue-triggered processing. The 409 ContainerAlreadyExists warnings continue well beyond startup and align with existing minute-based timer executions.

These appear consistent with the timer schedule monitor calling CreateIfNotExistsAsync() when saving status, with the handled 409 response still logged as a warning.

The suggested "Azure.Core": "Error" workaround also suppresses potentially actionable SDK warnings. Could these expected, handled responses be excluded from warning-level logging, or could a narrower filtering mechanism be provided?
