### ISSUE TITLE
ServiceBusTrigger w/Autocomplete = False does not work when processing  multiple messages.

### ISSUE THREAD

**Issue by kristoffervfs** [Azure/Azure-Functions#2254]
Hi, I am creating an function which needs to process multiple messages at the same time and with control of which messages in that batch is completed or not. 

By setting ```` Autocomplete = false ```` in host.json this works as expected:

````
[FunctionName("BatchProcessingFunc")]
public async Task Run(
    [ServiceBusTrigger("queuename", Connection = "queueconnection")] Message myQueueItem, 
    MessageReceiver messageReceiver, 
    ILogger log)
{

    log.LogInformation($"C# ServiceBus queue trigger function processed message: {myQueueItem}");
    await messageReceiver.CompleteAsync(myQueueItem.SystemProperties.LockToken);        
}
````

However if I change to receiving bulk messages by replacing ```` Message ```` with ```` Message[]```` the code throws an exception after the function is executed. 
New code for processing multiple:
````
[FunctionName("BatchProcessingFunc")]
public async Task Run(
    [ServiceBusTrigger("queuename", Connection = "queueconnection")] Message[] myQueueItem, 
    MessageReceiver messageReceiver, 
    ILogger log)
{

    foreach(var message in myQueueItem)
    {
        log.LogInformation($"C# ServiceBus queue trigger function processed message: {message}");
        await messageReceiver.CompleteAsync(message.SystemProperties.LockToken);
    }           
}
````
The exception thrown is:
````
Microsoft.Azure.ServiceBus.MessageLockLostException: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue, or was received by a different receiver instance.
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.DisposeMessagesAsync(IEnumerable`1 lockTokens, Outcome outcome)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.CompleteAsync(IEnumerable`1 lockTokens)
   at Microsoft.Azure.WebJobs.ServiceBus.Listeners.ServiceBusListener.<>c__DisplayClass35_0.<<StartMessageBatchReceiver>b__0>d.MoveNext()
````

It seems like the SDK tries to autoclose the messages once more after I've already done it, even though i have told it not to. And it only happens once i change from ```` Message ```` to ```` Message[] ````

Thanks

**Comment by ramya894** [comment]
@kristoffervfs Please refer the link provided below, in case you still face the issue please let us know in comments.

https://stackoverflow.com/questions/62752905/azure-function-service-bus-trigger-running-multiple-times
