### ISSUE TITLE
cannot run function app locally after updating to dot net 7

### ISSUE THREAD

**Issue by tnlthanzeel** [Azure/Azure-Functions#2295]
hi all. i have updated my function app to dotnet 7 and when i try to run the function app locally in debug mode i get the bellow error. but when i change the dotnet version to 6 it works.

Could not load file or assembly 'Microsoft.Extensions.Configuration.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.'

error details below.

System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'Microsoft.Extensions.Configuration.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
  Source=VPMS.FuncApp
  StackTrace:
   at VPMS.FuncApp.Startup.Configure(IFunctionsHostBuilder builder) in C:\Projects\Legacy HealthCare - Vendor Payment Management System\VPMS\VPMS.AzFunctionApps\VPMS.FuncApp\Startup.cs:line 41
   at Microsoft.Azure.WebJobs.WebJobsBuilderExtensions.ConfigureStartup(IWebJobsStartup startup, WebJobsBuilderContext context, IWebJobsBuilder builder) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Hosting\WebJobsBuilderExtensions.cs:line 162
   at Microsoft.Azure.WebJobs.WebJobsBuilderExtensions.ConfigureAndLogUserConfiguredServices(IWebJobsStartup startup, WebJobsBuilderContext context, IWebJobsBuilder builder, ILoggerFactory loggerFactory) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Hosting\WebJobsBuilderExtensions.cs:line 130
   at Microsoft.Azure.WebJobs.WebJobsBuilderExtensions.UseWebJobsStartup(IWebJobsBuilder builder, Type startupType, WebJobsBuilderContext context, ILoggerFactory loggerFactory) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Hosting\WebJobsBuilderExtensions.cs:line 115
   at Microsoft.Azure.WebJobs.WebJobsBuilderExtensions.UseExternalStartup(IWebJobsBuilder builder, IWebJobsStartupTypeLocator startupTypeLocator, WebJobsBuilderContext context, ILoggerFactory loggerFactory) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Hosting\WebJobsBuilderExtensions.cs:line 213
   at Microsoft.Azure.WebJobs.Script.ScriptHostBuilderExtensions.<>c__DisplayClass7_0.<AddScriptHostCore>b__1(HostBuilderContext context, IWebJobsBuilder webJobsBuilder)
   at Microsoft.Extensions.Hosting.WebJobsHostBuilderExtensions.<>c__DisplayClass5_0.<ConfigureWebJobs>b__1(HostBuilderContext context, IServiceCollection services) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Hosting\WebJobsHostBuilderExtensions.cs:line 54
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.<UnsynchronizedStartHostAsync>d__52.MoveNext()

my function app csproj

<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="3.4.2" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage.Queues" Version="5.0.1" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.1.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\VPMS.Persistence\VPMS.Persistence.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>

**Comment by railooforsea** [comment]
Similar problem when using .NET  7, i get this when running locally : 

Executed 'Function1' (Failed, Id=41ae3a98-8172-4d06-8203-29d9de33d42f, Duration=231ms)
[2022-11-10T12:05:09.510Z] System.Private.CoreLib: Exception while executing function: Function1. FunctionApp1: Could not load file or assembly 'System.Linq.Expressions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

.NET 6 - no problems.

**Comment by RedArrowITUK** [comment]
I get the System.Linq.Expressions issue as well.  I'm upgrading from .NET 3.1 and had to pick .NET 6 to get it working.  

I've had various issues like this in the past and had to set _FunctionsSkipCleanOutput to true in the csproj.  Has something changed in this area?

**Comment by avisra** [comment]
I'm seeing this error when it is deployed as well

**Comment by mprattinger** [comment]
I get a similar error, no whether i run .net 6 or .net 7:
Could not load file or assembly 'Microsoft.Azure.WebJobs.Script, Version=4.12.0.0.

i tried to repair visual studio, updated the azure function tools via visual studio, updatet azure function core tools, then completely delete the core tools. But the error is still the same.

**Comment by avisra** [comment]
I had to roll back to .NET 6 for this to function properly. Seems to be related to when I have the custom FunctionsStartup (vs just main in Program.cs) using microsoft.azure.functions.extensions.

**Comment by kshyju** [comment]
.NET 7 support was announced only for isolated model, not for in-proc model.

> _You can now build your serverless applications with .NET 7 in Azure Functions using the [.NET Isolated Worker model](https://docs.microsoft.com/azure/azure-functions/dotnet-isolated-process-guide), which provides an isolation model that decouples your function process from the Azure Functions runtime, bringing the flexibility needed to target different versions of .NET, more efficiently manage dependencies and service registration._

https://devblogs.microsoft.com/dotnet/dotnet-7-comes-to-azure-functions/#whats-new-in-net-7-with-azure-functions

Hope this helps. If you are having trouble to switch to .net 7 in isolated model app, please open an issue in the [dotnet isolated worker repo](https://github.com/Azure/azure-functions-dotnet-worker).

**Comment by ramya894** [comment]
closing as resolved
