### ISSUE TITLE
"No job functions found" on node runtime with import statement

### ISSUE THREAD

**Issue by jurijsk** [Azure/Azure-Functions#2368]
Function App name: **textjoint-fresh-api**
Tools used: 
* vs code. Not relevant, I can repro the changing the function file directly from Kudu console.
* `az --version`
```
azure-cli                         2.48.1
core                              2.48.1
telemetry                          1.0.8
Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0
```
* Runtime version: 4.19.0.20414

New V4 app or existing V3 app migrated to V4: **New**
**repo**: https://github.com/jurijsk/azure-func-issue-one 

**Problem**

I get very strange behavior from node Azure Function, which I can not constantly reproduce on any function app, of just created function app, and can not tell exactly what makes it recover.

Most certain and most often reproducible one line change is demoed in [this repo](https://github.com/jurijsk/azure-func-issue-one ). 
If the import statement for `@azure/storage-blob` is comment out the Function App will recover and both job functions will work.

**Steps to reproduce**
1. Open ./dist/test.js and toggle comment for `import { BlobServiceClient } from '@azure/storage-blob';` (line 2)
2. Deploy `func azure functionapp publish textjoint-fresh-api --nozip`
3. Navigate to [https://textjoint-fresh-api.azurewebsites.net/test](https://textjoint-fresh-api.azurewebsites.net/test) or [~/v](https://textjoint-fresh-api.azurewebsites.net/v)

When the import is commented the response will be normal with status 200.
When import is uncommented none of the functions will be discovered and both return 404.

_now deployed with import uncommented causing 404_

For runs with no job functions the log contains "No job functions found." and sometimes timeout exception (see below). 

```
2023-05-01T15:33:29.009 [Information] Reading functions metadata
2023-05-01T15:33:29.009 [Information] 1 functions found //>>should be 2 functions
2023-05-01T15:33:29.009 [Debug] Handling WorkerErrorEvent for runtime:node, workerId:node. Failed with: System.TimeoutException: The operation has timed out.
   at Microsoft.Azure.WebJobs.Script.Grpc.GrpcWorkerChannel.PendingItem.OnTimeout() in /_/src/WebJobs.Script.Grpc/Channel/GrpcWorkerChannel.cs:line 1452
--- End of stack trace from previous location ---
   at Microsoft.Azure.WebJobs.Script.Grpc.GrpcWorkerChannel.StartWorkerProcessAsync(CancellationToken cancellationToken) in /_/src/WebJobs.Script.Grpc/Channel/GrpcWorkerChannel.cs:line 275
2023-05-01T15:33:29.010 [Debug] Attempting to dispose webhost or jobhost channel for workerId: 'cd1291e8-c713-4747-9a1d-63083beb9e31', runtime: 'node'
2023-05-01T15:33:29.010 [Debug] Did not find WebHost or JobHost channel to dispose for workerId: 'cd1291e8-c713-4747-9a1d-63083beb9e31', runtime: 'node'
2023-05-01T15:33:29.010 [Debug] Skipping worker channel restart for errored worker runtime: 'node', current runtime: 'node', isWebHostChannel: 'False', isJobHostChannel: 'False'
2023-05-01T15:33:29.013 [Information] 0 functions loaded
2023-05-01T15:33:29.017 [Debug] Adding Function descriptor provider for language node.
2023-05-01T15:33:29.018 [Debug] Creating function descriptors.
2023-05-01T15:33:29.018 [Debug] Function descriptors created.
2023-05-01T15:33:29.018 [Debug] Placeholder mode is enabled: False
2023-05-01T15:33:29.019 [Debug] RpcFunctionInvocationDispatcher received no functions
2023-05-01T15:33:29.019 [Information] Generating 0 job function(s) //>>wat?
2023-05-01T15:33:29.026 [Warning] No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).

```

But timeout exception "required" to faild to discover job functions.

```
2023-05-02T09:34:36  Fetching changes.
2023-05-02T09:34:36    Cleaning up temp folders from previous zip deployments and extracting pushed zip file C:\local\Temp\zipdeploy\2hfnurun.zip (30.24 MB) to C:\local\Temp\zipdeploy\extracted
2023-05-02T09:34:44  Updating submodules.
2023-05-02T09:34:44  Preparing deployment for commit id '9b8101ac3a'.
2023-05-02T09:34:45  Generating deployment script.
2023-05-02T09:34:45    Using cached version of deployment script (command: 'azure -y --no-dot-deployment -r "C:\local\Temp\zipdeploy\extracted" -o "C:\home\site\deployments\tools" --basic --sitePath "C:\local\Temp\zipdeploy\extracted"').
2023-05-02T09:34:45  Running deployment command...
2023-05-02T09:34:45    Command: "C:\home\site\deployments\tools\deploy.cmd"
2023-05-02T09:34:46    Handling Basic Web Site deployment.
2023-05-02T09:34:46.705 [Information] File change of type 'Created' detected for 'C:\home\site\wwwroot\app_offline.htm'
2023-05-02T09:34:46.705 [Information] Host configuration has changed. Signaling shutdown
2023-05-02T09:34:46.706 [Information] File change of type 'Created' detected for 'C:\home\site\wwwroot\app_offline.htm'
2023-05-02T09:34:46.706 [Information] Host configuration has changed. Signaling restart
2023-05-02T09:34:46.718 [Debug] Hosting stopping
2023-05-02T09:34:46.719 [Debug] Stopping file watchers.
2023-05-02T09:34:46.741 [Debug] Waiting for RpcFunctionInvocationDispatcher to shutdown
2023-05-02T09:34:46.742 [Debug] Draining invocations from language worker channel timed out. Shutting down 'RpcFunctionInvocationDispatcher'
2023-05-02T09:34:46.742 [Information] Stopping JobHost
2023-05-02T09:34:46.742 [Debug] Stopping ScriptHost instance '511eb8da-2ea5-4ec1-8d64-028fd65df64c'.
2023-05-02T09:34:46.742 [Information] Job host stopped
2023-05-02T09:34:46.742 [Debug] Stopped ScriptHost instance '511eb8da-2ea5-4ec1-8d64-028fd65df64c'.
2023-05-02T09:34:46.745 [Debug] Hosting stopped
2023-05-02T09:34:46.745 [Debug] Disposing ScriptHost.
2023-05-02T09:34:46.746 [Debug] Disposing ScriptHost instance '511eb8da-2ea5-4ec1-8d64-028fd65df64c'.
2023-05-02T09:34:46.746 [Debug] Disposing FunctionDispatcher
2023-05-02T09:34:46.746 [Debug] Disposed ScriptHost instance '511eb8da-2ea5-4ec1-8d64-028fd65df64c'.
2023-05-02T09:34:46.764 [Debug] Host instance 'e80571af46669605cdb41165b9c21eec' released lock lease.
2023-05-02T09:34:46.764 [Debug] Disposing ScriptHost instance '511eb8da-2ea5-4ec1-8d64-028fd65df64c'.
2023-05-02T09:34:46.764 [Debug] Disposed ScriptHost instance '511eb8da-2ea5-4ec1-8d64-028fd65df64c'.
2023-05-02T09:34:51    Creating app_offline.htm
2023-05-02T09:34:51    KuduSync.NET from: 'C:\local\Temp\zipdeploy\extracted' to: 'C:\home\site\wwwroot'
2023-05-02T09:34:52    Deleting app_offline.htm
2023-05-02T09:34:52    Finished successfully.
2023-05-02T09:34:52  Running post deployment command(s)...
2023-05-02T09:34:52  Triggering recycle (preview mode disabled).
2023-05-02T09:34:52  Deployment successful.
2023-05-02T09:35:22.674 [Debug] Workers Directory set to: C:\Program Files (x86)\SiteExtensions\Functions\4.19.0\workers
2023-05-02T09:35:22.687 [Debug] Found worker config: C:\Program Files (x86)\SiteExtensions\Functions\4.19.0\workers\dotnet-isolated\worker.config.json
2023-05-02T09:35:22.688 [Debug] EnvironmentVariable FUNCTIONS_WORKER_RUNTIME: node
2023-05-02T09:35:22.688 [Information] FUNCTIONS_WORKER_RUNTIME set to node. Skipping WorkerConfig for language: dotnet-isolated
2023-05-02T09:35:22.689 [Debug] Found worker config: C:\Program Files (x86)\SiteExtensions\Functions\4.19.0\workers\java\worker.config.json
2023-05-02T09:35:22.689 [Debug] EnvironmentVariable FUNCTIONS_WORKER_RUNTIME: node
2023-05-02T09:35:22.689 [Information] FUNCTIONS_WORKER_RUNTIME set to node. Skipping WorkerConfig for language: java
2023-05-02T09:35:22.690 [Debug] Found worker config: C:\Program Files (x86)\SiteExtensions\Functions\4.19.0\workers\node\worker.config.json
2023-05-02T09:35:22.690 [Debug] EnvironmentVariable FUNCTIONS_WORKER_RUNTIME: node
2023-05-02T09:35:22.690 [Debug] EnvironmentVariable FUNCTIONS_WORKER_RUNTIME_VERSION: ~18
2023-05-02T09:35:22.690 [Debug] Added WorkerConfig for language: node
2023-05-02T09:35:22.691 [Debug] Found worker config: C:\Program Files (x86)\SiteExtensions\Functions\4.19.0\workers\powershell\worker.config.json
2023-05-02T09:35:22.691 [Debug] EnvironmentVariable FUNCTIONS_WORKER_RUNTIME: node
2023-05-02T09:35:22.691 [Information] FUNCTIONS_WORKER_RUNTIME set to node. Skipping WorkerConfig for language: powershell
2023-05-02T09:35:22.723 [Debug] Using BlobLeaseDistributedLockManager
2023-05-02T09:35:22.732 [Information] Initializing Warmup Extension.
2023-05-02T09:35:22.745 [Information] Initializing Host. OperationId: 'c771d19f-e085-465d-b36e-deda980c94fd'.
2023-05-02T09:35:22.753 [Information] Host initialization: ConsecutiveErrors=0, StartupCount=1, OperationId=c771d19f-e085-465d-b36e-deda980c94fd
2023-05-02T09:35:22.766 [Debug] Hosting starting
2023-05-02T09:35:22.786 [Information] ApplicationInsightsLoggerOptions
[..]
2023-05-02T09:35:22.786 [Information] LoggerFilterOptions
[..]
2023-05-02T09:35:22.786 [Information] LoggerFilterOptions
[..]
2023-05-02T09:35:22.786 [Information] ConcurrencyOptions
[..]
2023-05-02T09:35:22.787 [Information] FunctionResultAggregatorOptions
[..]
2023-05-02T09:35:22.787 [Information] SingletonOptions
[..]
2023-05-02T09:35:22.789 [Information] Starting JobHost
2023-05-02T09:35:22.791 [Information] Starting Host (HostId=azure-func-issue-one, InstanceId=b4dd6e4a-46c3-40f1-b3e9-1cf93be28760, Version=4.19.0.20414, ProcessId=7324, AppDomainId=1, InDebugMode=False, InDiagnosticMode=False, FunctionsExtensionVersion=~4)
2023-05-02T09:35:22.812 [Information] Loading functions metadata
2023-05-02T09:35:22.828 [Information] Reading functions metadata
2023-05-02T09:35:22.837 [Information] 1 functions found
2023-05-02T09:35:22.842 [Information] 0 functions loaded
2023-05-02T09:35:22.849 [Debug] Adding Function descriptor provider for language node.
2023-05-02T09:35:22.858 [Debug] Creating function descriptors.
2023-05-02T09:35:22.860 [Debug] Function descriptors created.
2023-05-02T09:35:22.861 [Debug] Placeholder mode is enabled: False
2023-05-02T09:35:22.861 [Debug] RpcFunctionInvocationDispatcher received no functions
2023-05-02T09:35:22.861 [Information] Generating 0 job function(s)
2023-05-02T09:35:22.871 [Warning] No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
2023-05-02T09:35:22.875 [Information] Initializing function HTTP routes
No HTTP routes mapped
2023-05-02T09:35:22.880 [Information] Host initialized (80ms)
2023-05-02T09:35:22.896 [Information] Host started (100ms)
2023-05-02T09:35:22.896 [Information] Job host started
2023-05-02T09:35:22.899 [Information] HttpOptions
[..]
2023-05-02T09:35:22.904 [Debug] File event source initialized.
2023-05-02T09:35:22.905 [Debug] Hosting started
2023-05-02T09:35:27.897 [Information] Host lock lease acquired by instance ID 'e80571af46669605cdb41165b9c21eec'.
2023-05-02T09:35:27.919 [Debug] Debug file watch initialized.
2023-05-02T09:35:27.920 [Debug] Diagnostic file watch initialized.
2023-05-02T09:35:52.895 [Debug] Initiating background SyncTriggers operation
2023-05-02T09:35:52.905 [Information] Loading functions metadata
2023-05-02T09:35:52.930 [Information] Reading functions metadata
2023-05-02T09:35:52.931 [Information] 1 functions found
2023-05-02T09:35:52.932 [Information] 0 functions loaded
2023-05-02T09:35:52.954 [Information] Loading functions metadata
2023-05-02T09:35:52.955 [Information] Reading functions metadata
2023-05-02T09:35:52.955 [Information] 1 functions found
2023-05-02T09:35:52.956 [Information] 0 functions loaded
2023-05-02T09:35:54.490 [Information] Loading functions metadata
2023-05-02T09:35:54.492 [Information] Reading functions metadata
2023-05-02T09:35:54.492 [Information] 1 functions found
2023-05-02T09:35:54.492 [Information] 0 functions loaded
```

I gather that Azure Infrastructure should run my function files to get meta and build routing and know what to run when. Can I at least get any logs from node to see that breaks?

## Context

* I have to run it from filesystem, not from package. I will need to use *.exe utility to access files and write back to the file. So I've removed `WEBSITE_RUN_FROM_PACKAGE`
* I've seen this behavior on a couple of Azure Functions, for this bug report created all new function, `azure-func-issue-one` but so far can not reproduce the same behavior on it with the same code base.
* I deploy using `func azure functionapp publish textjoint-fresh-api --nozip` While testing I was changing the `./dist/test.js` file directly via Kudu and App Service Editor, which require Function restart but ultimately lead to the same outcome.

I would love to understand that causes the problem, how to workaround and how to avoid.

**Comment by vijaykumar911** [comment]
HI  @jurijsk  check and update you.

**Comment by vijaykumar911** [comment]
It  could be a compatibility problem between the @azure/storage-blob package and the function app's runtime environment. Another reason could be a problem with the deployment process, where the package is not installed correctly on the function app. 

if the @azure/storage-blob package is installed correctly on the function app. You can use Kudu console to navigate to the function app's directory and check the node_modules folder for the package.

Check if the package version used in the function app is compatible with the function app's runtime environment. You can refer to the package documentation for compatibility information.
