### ISSUE TITLE
HttpTriggerJava local run failed 

### ISSUE THREAD

**Issue by wukong121** [Azure/Azure-Functions#2403]
I followed the [official manual](https://learn.microsoft.com/zh-cn/azure/azure-functions/functions-create-maven-intellij ) step by step and tried run HttpTriggerJava locally. But I got the following bugs.
```
Extension bundle specified, skip install extension

Azure Functions Core Tools
Core Tools Version:       4.0.5274 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.23.0.20886

[2023-08-31T07:40:32.584Z] Failed to start Worker Channel. Process fileName: $JAVA_HOME$/bin/java
[2023-08-31T07:40:32.584Z] System.Diagnostics.Process: An error occurred trying to start process '$JAVA_HOME$/bin/java' with working directory '/private/var/folders/jq/0rgrmj_d0rd9kf_t7bkd_jnm0000gq/T/azure-functions8927741848205707219'. No such file or directory.
[2023-08-31T07:40:32.596Z] Failed to start a new language worker for runtime: java.
[2023-08-31T07:40:32.596Z] System.Diagnostics.Process: An error occurred trying to start process '$JAVA_HOME$/bin/java' with working directory '/private/var/folders/jq/0rgrmj_d0rd9kf_t7bkd_jnm0000gq/T/azure-functions8927741848205707219'. No such file or directory.

Functions:

	HttpTriggerJava: [GET,POST] http://localhost:63172/api/HttpTriggerJava

For detailed output, run func with --verbose flag.
[2023-08-31T07:40:37.477Z] Host lock lease acquired by instance ID '000000000000000000000000EEB36798'.
[2023-08-31T07:41:32.571Z] Starting worker process failed
[2023-08-31T07:41:32.571Z] Microsoft.Azure.WebJobs.Script.Grpc: The operation has timed out.
[2023-08-31T07:41:32.603Z] Failed to start Worker Channel. Process fileName: $JAVA_HOME$/bin/java
[2023-08-31T07:41:32.603Z] System.Diagnostics.Process: An error occurred trying to start process '$JAVA_HOME$/bin/java' with working directory '/private/var/folders/jq/0rgrmj_d0rd9kf_t7bkd_jnm0000gq/T/azure-functions8927741848205707219'. No such file or directory.
Unhandled exception. System.ComponentModel.Win32Exception (2): An error occurred trying to start process '$JAVA_HOME$/bin/java' with working directory '/private/var/folders/jq/0rgrmj_d0rd9kf_t7bkd_jnm0000gq/T/azure-functions8927741848205707219'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.Azure.WebJobs.Script.Workers.WorkerProcess.StartProcessAsync() in /_/src/WebJobs.Script/Workers/ProcessManagement/WorkerProcess.cs:line 75
--- End of stack trace from previous location ---
   at Microsoft.Azure.WebJobs.Script.Grpc.GrpcWorkerChannel.StartWorkerProcessAsync(CancellationToken cancellationToken) in /_/src/WebJobs.Script.Grpc/Channel/GrpcWorkerChannel.cs:line 281
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.InitializeJobhostLanguageWorkerChannelAsync(Int32 attemptCount, IEnumerable`1 languages) in /_/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 152
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.InitializeJobhostLanguageWorkerChannelAsync(Int32 attemptCount, String language) in /_/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 144
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.StartWorkerChannel(String runtime) in /_/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 583
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.StartWorkerChannel(String runtime) in /_/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 595
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.DisposeAndRestartWorkerChannel(String runtime, String workerId, Exception workerException) in /_/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 545
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.WorkerError(WorkerErrorEvent workerError) in /_/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 459
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
Failed to run function CLI command from staging folder(azure-functions8927741848205707219),    at System.Threading.Thread.StartCallback().
```
The version of tools are below
```
Core Tools Version:       4.0.5274
Function Runtime Version: 4.23.0.20886
JDK: corretto-11.0.20.1
Maven: 3.9.2
```
I already set the true JAVA_HOME variable.
<img width="1404" alt="Screenshot 2023-08-31 at 16 08 25" src="https://github.com/Azure/Azure-Functions/assets/79131635/83337f91-4664-4bb8-b2e5-fec703d66e00">

**Comment by bhagyshricompany** [comment]
Thanks for reporting will check

**Comment by pbControl** [comment]
Be careful with your JAVA_HOME setting in intellij.  I've just had probably the same issue and it was because intellij was appending ./bin/java to it.

**Comment by MonishaRudraswamy** [comment]
How to remove this appending in in Intellij

**Comment by NirajKuma4r** [comment]
You remove the "/bin/java" from Azure.Functions.Cli.win-x86.4.0.5858\workers\java\worker.config.json
old  = "%JAVA_HOME%/bin/java
updated = "%JAVA_HOME%/

**Comment by VineethReyya** [comment]
@wukong121 Is this issue still existing?

**Comment by VineethReyya** [comment]
We are closing this ticket due to a lack of recent activity. If the issue still persists, please feel free to open a new ticket, and we will be happy to assist you further.

Thank you for your understanding!
