### ISSUE TITLE
Metadata generation failed. after updating to .Net 8 

### ISSUE THREAD

**Issue by doorman02** [Azure/Azure-Functions#2423]
Hi,

I am upgrading my Azure Functions app to .net 8 but when I build the project i get the following error:

```
Microsoft.NET.Sdk.Functions.Build.targets(32,5): Error  : System.NullReferenceException: Object reference not set to an instance of an object.

   at MakeFunctionJson.AttributeExtensions.IsWebJobsAttribute(CustomAttribute attribute) in /_/src/Microsoft.NET.Sdk.Functions.Generator/AttributeExtensions.cs:line 52

   at MakeFunctionJson.ParameterInfoExtensions.<>c.<ToFunctionJsonBindings>b__1_0(CustomAttribute a) in /_/src/Microsoft.NET.Sdk.Functions.Generator/ParameterInfoExtensions.cs:line 31

   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToList()

   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

   at MakeFunctionJson.ParameterInfoExtensions.ToFunctionJsonBindings(ParameterDefinition parameterInfo) in /_/src/Microsoft.NET.Sdk.Functions.Generator/ParameterInfoExtensions.cs:line 29

   at MakeFunctionJson.MethodInfoExtensions.<>c.<ToFunctionJson>b__6_0(ParameterDefinition p) in /_/src/Microsoft.NET.Sdk.Functions.Generator/MethodInfoExtensions.cs:line 66

   at System.Linq.Enumerable.SelectIListIterator`2.MoveNext()

   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()

   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)

   at System.Collections.Generic.SparseArrayBuilder`1.AddRange(IEnumerable`1 items)

   at System.Collections.Generic.SparseArrayBuilder`1.ReserveOrAdd(IEnumerable`1 items)

   at System.Linq.Enumerable.Concat2Iterator`1.ToArray()

   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)

   at MakeFunctionJson.MethodInfoExtensions.ToFunctionJson(MethodDefinition method, String assemblyPath) in /_/src/Microsoft.NET.Sdk.Functions.Generator/MethodInfoExtensions.cs:line 65

   at MakeFunctionJson.FunctionJsonConverter.GenerateFunctions(IEnumerable`1 types)+MoveNext() in /_/src/Microsoft.NET.Sdk.Functions.Generator/FunctionJsonConverter.cs:line 140

   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

   at MakeFunctionJson.FunctionJsonConverter.TryGenerateFunctionJsons() in /_/src/Microsoft.NET.Sdk.Functions.Generator/FunctionJsonConverter.cs:line 194

   at MakeFunctionJson.FunctionJsonConverter.TryRun() in /_/src/Microsoft.NET.Sdk.Functions.Generator/FunctionJsonConverter.cs:line 87

Error generating functions metadata

1>Microsoft.NET.Sdk.Functions.Build.targets(32,5): Error  : Metadata generation failed.
```

Here is the node inside the Microsoft.NET.Sdk.Functions.Build.targets file

```
<GenerateFunctions
  TargetPath="$(TargetDir)bin\$(TargetFileName)"
  OutputPath="$(TargetDir)"
  UserProvidedFunctionJsonFiles="@(UserProvidedFunctionJsonFiles)" 
  FunctionsInDependencies="$(FunctionsInDependencies)"
  TaskAssemblyDirectory="$(_FunctionsTasksDir)"/>
```
Building it on:
macOS 14.1.1
Microsoft.NET.Sdk.Functions v 4.2.0

When building the project in .Net6 it worked fine.

Any idea how to solve this issue?

Thanks!

**Comment by doorman02** [comment]
the issue was an optional parameter in the endpoint parameter. So I removed the ? and it built. 
e.g. 
 ```
[Route("api/books/locale/{lcid:int?}")]
  public IEnumerable<Book> GetBooksByLocale(int(?) lcid = 1033) { ... }
```
removed the (?)
