### ISSUE TITLE
Isolated process HttpTriggers Custom Middleware response.WriteAsJsonAsync creates an exception

### ISSUE THREAD

**Issue by EnenDaveyBoy** [Azure/Azure-Functions#2505]
<FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.21.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.1.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="1.2.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.17.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.22.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="1.2.0" />

in c# net8 V4 InProcess LTS azure functions

If in middleware i create a response which usings WriteAsJsonAsync is causes the following Exception

``
An attempt was made to transition a task to a final state when it had already completed.
``

if I change it to WriteStringAsync i don't get the exception, it would be nice to have the same availability to return json.

This only happens in custom middlware but no matter where i put it i still get the same exception, this only happens after the return of the middleware takes place but it is the WriteStringAsync  that causes the exception

``
public async Task Invoke(FunctionContext context, FunctionExecutionDelegate next)
        {
            
            var requestData = await context.GetHttpRequestDataAsync() ?? throw new InvalidOperationException(nameof(HttpRequestData));

            // await new CorsResponse(context, requestData, _log).ErrorAsync("testing", "something ");
            // return;

            var foo = "foo";
            var bar = "bar";

            _log.LogInformation("setting error response");
                var responseData =requestData.CreateResponse();
                responseData.Headers.Add("foo", "bar");
                _log.LogInformation("error {0} {1}", "error", "errorDescription");
                    await responseData.WriteAsJsonAsync(new 
                        {
                            foo,
                            bar
                        }, HttpStatusCode.Unauthorized
                    );
                _log.LogInformation("set error response");
                context.GetInvocationResult().Value = responseData;
                _log.LogInformation("added error response to invocation result");

            return;
``

on a side note WriteAsJsonAsync  also always resets the stattus code to OK another annoying function of WriteAsJsonAsync if i set it in create it should stay what i set it.

**Comment by bhagyshricompany** [comment]
Hi @EnenDaveyBoy  thanks for updating please share the all repro steps.

**Comment by EnenDaveyBoy** [comment]
Hi

Create a c# function isolated lts net8 (although its the same error in net6),

Create the middleware

``
using System.Net;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Azure.Functions.Worker.Http;
using Microsoft.Azure.Functions.Worker.Middleware;
using Microsoft.Extensions.Logging;

namespace MyMiddleware
{
    public class ResponseMiddleware : IFunctionsWorkerMiddleware
    {
        private readonly ILogger _log;
        public ResponseMiddleware(ILoggerFactory log)
        {
            _log = log.CreateLogger<ResponseMiddleware>();
        }

        public async Task Invoke(FunctionContext context, FunctionExecutionDelegate next)
        {
             _log.LogInformation("start middleware");

            var response = context.GetHttpResponseData();

            if(response is null)
            {
                _log.LogInformation("no response found, creating OK response");
                var request = await context.GetHttpRequestDataAsync() ?? throw new ArgumentNullException("http request cannot be null");
                response = request.CreateResponse();
            }

            await response.WriteAsJsonAsync(new {
                foo = "foo",
                bar = "bar"
            }, HttpStatusCode.OK);


            context.GetInvocationResult().Value = response;

            
            await next(context); 
        }  
    }
}
``

register the middleware

``
using Microsoft.Azure.Functions.Worker;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.DependencyInjection;
using MyMiddleware;

var host = new HostBuilder()
    .ConfigureFunctionsWebApplication(s => {
        s.UseMiddleware<ResponseMiddleware>();
    })
    .ConfigureServices(services => {
        services.AddApplicationInsightsTelemetryWorkerService();
        services.ConfigureFunctionsApplicationInsights();
    })
    .Build();

host.Run();
``

run the function, get the following error

``
Function 'Functions', Invocation id 'b9a97e0e-9ae2-4ea0-8b32-27177c6d232e': An exception was thrown by the invocation.
[2024-06-25T11:30:51.175Z] Result: Function 'Functions', Invocation id 'b9a97e0e-9ae2-4ea0-8b32-27177c6d232e': An exception was thrown by the invocation.
Exception: System.InvalidOperationException: StatusCode cannot be set because the response has already started.
[2024-06-25T11:30:51.175Z]    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ThrowResponseAlreadyStartedException(String value)
[2024-06-25T11:30:51.176Z]    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.set_StatusCode(Int32 value)
[2024-06-25T11:30:51.177Z]    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.Microsoft.AspNetCore.Http.Features.IHttpResponseFeature.set_StatusCode(Int32 value)
[2024-06-25T11:30:51.177Z]    at Microsoft.AspNetCore.Http.DefaultHttpResponse.set_StatusCode(Int32 value)
[2024-06-25T11:30:51.178Z]    at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsyncCore(ActionContext context, ObjectResult result, Type objectType, Object value)
[2024-06-25T11:30:51.178Z]    at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsync(ActionContext context, ObjectResult result)
[2024-06-25T11:30:51.179Z]    at Microsoft.AspNetCore.Mvc.ObjectResult.ExecuteResultAsync(ActionContext context)
[2024-06-25T11:30:51.180Z]    at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\extensions\Worker.Extensions.Http.AspNetCore\src\FunctionsMiddleware\FunctionsHttpProxyingMiddleware.cs:line 56
[2024-06-25T11:30:51.181Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77
Stack:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ThrowResponseAlreadyStartedException(String value)
[2024-06-25T11:30:51.181Z]    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.set_StatusCode(Int32 value)
[2024-06-25T11:30:51.182Z]    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.Microsoft.AspNetCore.Http.Features.IHttpResponseFeature.set_StatusCode(Int32 value)
[2024-06-25T11:30:51.183Z]    at Microsoft.AspNetCore.Http.DefaultHttpResponse.set_StatusCode(Int32 value)
[2024-06-25T11:30:51.184Z]    at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsyncCore(ActionContext context, ObjectResult result, Type objectType, Object value)
[2024-06-25T11:30:51.184Z]    at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsync(ActionContext context, ObjectResult result)
[2024-06-25T11:30:51.185Z]    at Microsoft.AspNetCore.Mvc.ObjectResult.ExecuteResultAsync(ActionContext context)
[2024-06-25T11:30:51.186Z]    at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\extensions\Worker.Extensions.Http.AspNetCore\src\FunctionsMiddleware\FunctionsHttpProxyingMiddleware.cs:line 56
[2024-06-25T11:30:51.186Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77.
``

this error only happens when you add

``
await response.WriteAsJsonAsync(new {
                foo = "foo",
                bar = "bar"
            }, HttpStatusCode.OK);
``

if you remove or if you return a string its fine (i haven't tried returning a stream), i hope thats what you need

**Comment by bhagyshricompany** [comment]
ok thanks.will update .

**Comment by bhagyshricompany** [comment]
@fabiocav pls comment.

**Comment by EnenDaveyBoy** [comment]
i have also found in the same process that is i just WriteAsJsonAsync in the actual function it wipes out all headers

eg

``
[Function("en")]
        public async Task<HttpResponseData> GetAsync([HttpTrigger(AuthorizationLevel.Function, "get", Route = "{version}/universe/{universeId}/business/get")] HttpRequestData req,
        string version,
        string universeId)
        {
        var error = "error";
        var description = "description"
        HttpResponseData response = _httpRequest.CreateResponse(HttpStatusCode.OK);
        await response.WriteAsJsonAsync(new { error, description});
        response.Headers.Add("header","value");
        return response;
        }
``

the header will not be returned, this is the same for any header added through middleware.

another problem with WriteAsJsonAsync is it overwrites the status code in the CreateResponse(HttpStatus.BadRequest) or it you set it manually response.HttpStatus = HttpStatus.BadRequest to HttpStatus.Ok, unless you set it in the WriteAsJsonAsync

**Comment by EnenDaveyBoy** [comment]
i have figured out a work around, basically the creating a response with a body with a function deems the function complete and all of the methods after a functions response does not effect the response, in order to mitigate this, get the function to return a response without a body, store the body in the functioncontext then in the first/last middleware get the response and add the response and it works, its not clean but it works without issue.

with the however if you return WriteAsJsonAsync you will also need to add the httpstatuscode to the WriteAsJsonAsync  otherwise it will revert to Ok response.

**Comment by bhagyshricompany** [comment]
ok for  use please use the latest version <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="1.2.1" />and ref this doc https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.functions.worker.http.httpresponsedataextensions.writestringasync?view=azure-dotnet
