### ISSUE TITLE
Azure Function with .NET and AOT produces Exception: System.InvalidOperationException: Reflection-based serialization

### ISSUE THREAD

**Issue by shotyme** [Azure/Azure-Functions#2541]
Hi, 

when I create a new Azure Function v4 with .NET8 in isolated-worker mode and add 

```
<PropertyGroup>
 <PublishAot>true</PublishAot>
</PropertyGroup>
```

to the .csproj I get this exception on the startup:

```
Exception: System.InvalidOperationException: Reflection-based serialization has been disabled for this application. Either use the source generator APIs or explicitly configure the 'JsonSerializerOptions.TypeInfoResolver' property.
[2024-09-06T13:56:38.895Z]    at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonSerializerIsReflectionDisabled()
[2024-09-06T13:56:38.895Z]    at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
[2024-09-06T13:56:38.896Z]    at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type inputType)
[2024-09-06T13:56:38.897Z]    at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions options)
[2024-09-06T13:56:38.897Z]    at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
[2024-09-06T13:56:38.897Z]    at Microsoft.Azure.Functions.Worker.Grpc.FunctionMetadata.FunctionMetadataRpcExtensions.GetBindingInfoList(IFunctionMetadata funcMetadata) in D:\a\_work\1\s\src\DotNetWorker.Grpc\FunctionMetadata\FunctionMetadataRpcExtensions.cs:line 29
[2024-09-06T13:56:38.898Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.GetFunctionMetadataAsync(String functionAppDirectory) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 185
Stack:    at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonSerializerIsReflectionDisabled()
[2024-09-06T13:56:38.898Z]    at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
[2024-09-06T13:56:38.899Z]    at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type inputType)
[2024-09-06T13:56:38.899Z]    at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions options)
[2024-09-06T13:56:38.900Z]    at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
[2024-09-06T13:56:38.900Z]    at Microsoft.Azure.Functions.Worker.Grpc.FunctionMetadata.FunctionMetadataRpcExtensions.GetBindingInfoList(IFunctionMetadata funcMetadata) in D:\a\_work\1\s\src\DotNetWorker.Grpc\FunctionMetadata\FunctionMetadataRpcExtensions.cs:line 29
[2024-09-06T13:56:38.901Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.GetFunctionMetadataAsync(String functionAppDirectory) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 185.
[2024-09-06T13:56:38.935Z] Unhandled exception. System.InvalidOperationException: Reflection-based serialization has been disabled for this application. Either use the source generator APIs or explicitly configure the 'JsonSerializerOptions.TypeInfoResolver' property.
```

The Azure Function was created by the Visual Studio 2022 template and just contained the boilderplate HttpTrigger. If you remove the  `PublishAot` option from your csproj you should remove the `bin` and `obj` folder and it should start again. Same goes the other way around when you add it back in and you want to produce the issue again. 
Do I miss something here?

**Comment by KondzioSSJ4** [comment]
As far as I remember AoT is not supported by Azure Functions
To be honest... I would try to do some work to make AoT possible

Is there any threat or list of required job to make?

Most part what I think that would be required would be related to removing json files with configurations of the functions
and instead of that just making source generated precompiled parts
but... to make it easier I guessing the better would be starting with providing `VerifyTests/Verify.SourceGenerators` into project to make it easy to validate what generators generate

**Comment by bhagyshricompany** [comment]
why you using AOT.

**Comment by shotyme** [comment]
@bhagyshricompany I want to use AOT in my functions to have super fast Start-Up time. I read something like theoretical 2-3 times faster with AOT. This would be huge.
