### ISSUE TITLE
When trying to run a function locally on VS Code, grpc.FutureTimeoutError

### ISSUE THREAD

**Issue by yooontheearth** [Azure/Azure-Functions#2554]
- I followed this tutorial, [Quickstart: Create a function in Azure with Python using Visual Studio](https://learn.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-python)
  - [Manually install or update Core Tools](https://learn.microsoft.com/en-us/azure/azure-functions/functions-run-local#install-the-azure-functions-core-tools) as the tutorial suggested
  - Other requirements such as Azure Functions extension, etc are installed
  - Python version: 3.10.12
  - Ubuntu 22.04.2 LTS on WSL2 Windows 11

When I try to run a function locally by press F5 on Visual Studio Code, it gives me the following error,

```
Executing task: .venv/bin/python -m pip install -r requirements.txt 

Requirement already satisfied: azure-functions in ./.venv/lib/python3.10/site-packages (from -r requirements.txt (line 5)) (1.21.3)
 *  Terminal will be reused by tasks, press any key to close it. 

 *  Executing task: . .venv/bin/activate && func host start 

Found Python version 3.10.12 (python3).

Azure Functions Core Tools
Core Tools Version:       4.0.6280 Commit hash: N/A +421f0144b42047aa289ce691dc6db4fc8b6143e6 (64-bit)
Function Runtime Version: 4.834.3.22875

[2024-10-30T02:20:34.352Z]  ERROR: unhandled error in functions worker: 
[2024-10-30T02:20:34.958Z] Language Worker Process exited. Pid=31355.
[2024-10-30T02:20:34.958Z] python3 exited with code 1 (0x1). grpc.FutureTimeoutError,    raise grpc.FutureTimeoutError(),grpc.FutureTimeoutError.
[2024-10-30T02:21:29.024Z] Starting worker process failed
[2024-10-30T02:21:29.024Z] Microsoft.Azure.WebJobs.Script.Grpc: The operation has timed out.
[2024-10-30T02:21:29.025Z] Failed to start language worker process for runtime: python. workerId:aadc6c70-52f5-4331-bc15-5c0b2f691730
[2024-10-30T02:21:29.026Z] Removing errored webhost language worker channel for runtime: python workerId:aadc6c70-52f5-4331-bc15-5c0b2f691730
[2024-10-30T02:21:29.026Z] Microsoft.Azure.WebJobs.Script.Grpc: The operation has timed out.
[2024-10-30T02:21:29.514Z] Traceback (most recent call last):
[2024-10-30T02:21:29.514Z]   File "/usr/lib/azure-functions-core-tools-4/workers/python/3.10/LINUX/X64/azure_functions_worker/main.py", line 60, in main
[2024-10-30T02:21:29.514Z]     return asyncio.run(start_async(
[2024-10-30T02:21:29.514Z]   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
[2024-10-30T02:21:29.514Z]     return loop.run_until_complete(main)
[2024-10-30T02:21:29.514Z]   File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
[2024-10-30T02:21:29.514Z]     return future.result()
[2024-10-30T02:21:29.514Z]   File "/usr/lib/azure-functions-core-tools-4/workers/python/3.10/LINUX/X64/azure_functions_worker/main.py", line 72, in start_async
[2024-10-30T02:21:29.514Z]     disp = await dispatcher.Dispatcher.connect(host=host, port=port,
[2024-10-30T02:21:29.514Z]   File "/usr/lib/azure-functions-core-tools-4/workers/python/3.10/LINUX/X64/azure_functions_worker/dispatcher.py", line 134, in connect
[2024-10-30T02:21:29.514Z]     await disp._grpc_connected_fut
[2024-10-30T02:21:29.514Z]   File "/usr/lib/azure-functions-core-tools-4/workers/python/3.10/LINUX/X64/azure_functions_worker/dispatcher.py", line 955, in __poll_grpc
[2024-10-30T02:21:29.514Z]     grpc.channel_ready_future(channel).result(
[2024-10-30T02:21:29.514Z]   File "/usr/lib/azure-functions-core-tools-4/workers/python/3.10/LINUX/X64/grpc/_utilities.py", line 151, in result
[2024-10-30T02:21:29.514Z]     self._block(timeout)
[2024-10-30T02:21:29.515Z]   File "/usr/lib/azure-functions-core-tools-4/workers/python/3.10/LINUX/X64/grpc/_utilities.py", line 97, in _block
[2024-10-30T02:21:29.515Z]     raise grpc.FutureTimeoutError()
[2024-10-30T02:21:29.515Z] grpc.FutureTimeoutError
[2024-10-30T02:21:29.515Z] Traceback (most recent call last):
[2024-10-30T02:21:29.515Z]   File "/usr/lib/azure-functions-core-tools-4/workers/python/3.10/LINUX/X64/azure_functions_worker/main.py", line 60, in main
[2024-10-30T02:21:29.515Z]     return asyncio.run(start_async(
[2024-10-30T02:21:29.515Z]   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
[2024-10-30T02:21:29.515Z]     return loop.run_until_complete(main)
[2024-10-30T02:21:29.515Z]   File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
[2024-10-30T02:21:29.515Z]     return future.result()
[2024-10-30T02:21:29.515Z]   File "/usr/lib/azure-functions-core-tools-4/workers/python/3.10/LINUX/X64/azure_functions_worker/main.py", line 72, in start_async
[2024-10-30T02:21:29.515Z]     disp = await dispatcher.Dispatcher.connect(host=host, port=port,
[2024-10-30T02:21:29.515Z]   File "/usr/lib/azure-functions-core-tools-4/workers/python/3.10/LINUX/X64/azure_functions_worker/dispatcher.py", line 134, in connect
[2024-10-30T02:21:29.515Z]     await disp._grpc_connected_fut
[2024-10-30T02:21:29.515Z]   File "/usr/lib/azure-functions-core-tools-4/workers/python/3.10/LINUX/X64/azure_functions_worker/dispatcher.py", line 955, in __poll_grpc
[2024-10-30T02:21:29.515Z]     grpc.channel_ready_future(channel).result(
[2024-10-30T02:21:29.515Z]   File "/usr/lib/azure-functions-core-tools-4/workers/python/3.10/LINUX/X64/grpc/_utilities.py", line 151, in result
[2024-10-30T02:21:29.515Z]     self._block(timeout)
[2024-10-30T02:21:29.515Z]   File "/usr/lib/azure-functions-core-tools-4/workers/python/3.10/LINUX/X64/grpc/_utilities.py", line 97, in _block
[2024-10-30T02:21:29.515Z]     raise grpc.FutureTimeoutError()
[2024-10-30T02:21:29.515Z] grpc.FutureTimeoutError
[2024-10-30T02:21:29.515Z] Traceback (most recent call last):
[2024-10-30T02:21:29.515Z]   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[2024-10-30T02:21:29.515Z]     return _run_code(code, main_globals, None,
[2024-10-30T02:21:29.516Z]   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[2024-10-30T02:21:29.516Z]     exec(code, run_globals)
[2024-10-30T02:21:29.516Z]   File "/home/g6552/.vscode-server/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/__main__.py", line 71, in <module>
[2024-10-30T02:21:29.516Z]     cli.main()
[2024-10-30T02:21:29.516Z]   File "/home/g6552/.vscode-server/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/../debugpy/server/cli.py", line 501, in main
[2024-10-30T02:21:29.516Z]     run()
[2024-10-30T02:21:29.516Z]   File "/home/g6552/.vscode-server/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/../debugpy/server/cli.py", line 351, in run_file
[2024-10-30T02:21:29.516Z]     runpy.run_path(target, run_name="__main__")
[2024-10-30T02:21:29.516Z]   File "/home/g6552/.vscode-server/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 310, in run_path
[2024-10-30T02:21:29.516Z]     return _run_module_code(code, init_globals, run_name, pkg_name=pkg_name, script_name=fname)
[2024-10-30T02:21:29.516Z]   File "/home/g6552/.vscode-server/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 127, in _run_module_code
[2024-10-30T02:21:29.516Z]     _run_code(code, mod_globals, init_globals, mod_name, mod_spec, pkg_name, script_name)
[2024-10-30T02:21:29.516Z]   File "/home/g6552/.vscode-server/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 118, in _run_code
[2024-10-30T02:21:29.516Z]     exec(code, run_globals)
[2024-10-30T02:21:29.516Z]   File "/usr/lib/azure-functions-core-tools-4/workers/python/3.10/LINUX/X64/worker.py", line 71, in <module>
[2024-10-30T02:21:29.516Z]     main.main()
[2024-10-30T02:21:29.516Z]   File "/usr/lib/azure-functions-core-tools-4/workers/python/3.10/LINUX/X64/azure_functions_worker/main.py", line 60, in main
[2024-10-30T02:21:29.516Z]     return asyncio.run(start_async(
[2024-10-30T02:21:29.516Z]   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
[2024-10-30T02:21:29.516Z]     return loop.run_until_complete(main)
[2024-10-30T02:21:29.516Z]   File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
[2024-10-30T02:21:29.516Z]     return future.result()
[2024-10-30T02:21:29.516Z]   File "/usr/lib/azure-functions-core-tools-4/workers/python/3.10/LINUX/X64/azure_functions_worker/main.py", line 72, in start_async
[2024-10-30T02:21:29.517Z]     disp = await dispatcher.Dispatcher.connect(host=host, port=port,
[2024-10-30T02:21:29.517Z]   File "/usr/lib/azure-functions-core-tools-4/workers/python/3.10/LINUX/X64/azure_functions_worker/dispatcher.py", line 134, in connect
[2024-10-30T02:21:29.517Z]     await disp._grpc_connected_fut
[2024-10-30T02:21:29.517Z]   File "/usr/lib/azure-functions-core-tools-4/workers/python/3.10/LINUX/X64/azure_functions_worker/dispatcher.py", line 955, in __poll_grpc
[2024-10-30T02:21:29.517Z]     grpc.channel_ready_future(channel).result(
[2024-10-30T02:21:29.517Z]   File "/usr/lib/azure-functions-core-tools-4/workers/python/3.10/LINUX/X64/grpc/_utilities.py", line 151, in result
[2024-10-30T02:21:29.517Z]     self._block(timeout)
[2024-10-30T02:21:29.517Z]   File "/usr/lib/azure-functions-core-tools-4/workers/python/3.10/LINUX/X64/grpc/_utilities.py", line 97, in _block
[2024-10-30T02:21:29.517Z]     raise grpc.FutureTimeoutError()
[2024-10-30T02:21:29.517Z] grpc.FutureTimeoutError
[2024-10-30T02:21:34.871Z]  ERROR: unhandled error in functions worker: 
[2024-10-30T02:21:34.872Z] Traceback (most recent call last):
[2024-10-30T02:21:34.873Z]   File "/usr/lib/azure-functions-core-tools-4/workers/python/3.10/LINUX/X64/azure_functions_worker/main.py", line 60, in main
[2024-10-30T02:21:34.873Z]     return asyncio.run(start_async(
[2024-10-30T02:21:34.873Z]   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
[2024-10-30T02:21:34.873Z]     return loop.run_until_complete(main)
[2024-10-30T02:21:34.873Z]   File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
[2024-10-30T02:21:34.873Z]     return future.result()
[2024-10-30T02:21:34.873Z]   File "/usr/lib/azure-functions-core-tools-4/workers/python/3.10/LINUX/X64/azure_functions_worker/main.py", line 72, in start_async
[2024-10-30T02:21:34.873Z]     disp = await dispatcher.Dispatcher.connect(host=host, port=port,
[2024-10-30T02:21:34.873Z]   File "/usr/lib/azure-functions-core-tools-4/workers/python/3.10/LINUX/X64/azure_functions_worker/dispatcher.py", line 134, in connect
[2024-10-30T02:21:34.873Z]     await disp._grpc_connected_fut
[2024-10-30T02:21:34.873Z]   File "/usr/lib/azure-functions-core-tools-4/workers/python/3.10/LINUX/X64/azure_functions_worker/dispatcher.py", line 955, in __poll_grpc
[2024-10-30T02:21:34.873Z]     grpc.channel_ready_future(channel).result(
[2024-10-30T02:21:34.873Z]   File "/usr/lib/azure-functions-core-tools-4/workers/python/3.10/LINUX/X64/grpc/_utilities.py", line 151, in result
[2024-10-30T02:21:34.873Z]     self._block(timeout)
[2024-10-30T02:21:34.873Z]   File "/usr/lib/azure-functions-core-tools-4/workers/python/3.10/LINUX/X64/grpc/_utilities.py", line 97, in _block
[2024-10-30T02:21:34.873Z]     raise grpc.FutureTimeoutError()
[2024-10-30T02:21:34.873Z] grpc.FutureTimeoutError
[2024-10-30T02:21:34.873Z] Traceback (most recent call last):
[2024-10-30T02:21:34.873Z]   File "/usr/lib/azure-functions-core-tools-4/workers/python/3.10/LINUX/X64/azure_functions_worker/main.py", line 60, in main
[2024-10-30T02:21:34.873Z]     return asyncio.run(start_async(
[2024-10-30T02:21:34.873Z]   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
[2024-10-30T02:21:34.873Z]     return loop.run_until_complete(main)
[2024-10-30T02:21:34.873Z]   File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
[2024-10-30T02:21:34.873Z]     return future.result()
[2024-10-30T02:21:34.873Z]   File "/usr/lib/azure-functions-core-tools-4/workers/python/3.10/LINUX/X64/azure_functions_worker/main.py", line 72, in start_async
[2024-10-30T02:21:34.873Z]     disp = await dispatcher.Dispatcher.connect(host=host, port=port,
[2024-10-30T02:21:34.873Z]   File "/usr/lib/azure-functions-core-tools-4/workers/python/3.10/LINUX/X64/azure_functions_worker/dispatcher.py", line 134, in connect
[2024-10-30T02:21:34.873Z]     await disp._grpc_connected_fut
[2024-10-30T02:21:34.873Z]   File "/usr/lib/azure-functions-core-tools-4/workers/python/3.10/LINUX/X64/azure_functions_worker/dispatcher.py", line 955, in __poll_grpc
[2024-10-30T02:21:34.874Z]     grpc.channel_ready_future(channel).result(
[2024-10-30T02:21:34.874Z]   File "/usr/lib/azure-functions-core-tools-4/workers/python/3.10/LINUX/X64/grpc/_utilities.py", line 151, in result
[2024-10-30T02:21:34.874Z]     self._block(timeout)
[2024-10-30T02:21:34.874Z]   File "/usr/lib/azure-functions-core-tools-4/workers/python/3.10/LINUX/X64/grpc/_utilities.py", line 97, in _block
[2024-10-30T02:21:34.874Z]     raise grpc.FutureTimeoutError()
[2024-10-30T02:21:34.874Z] grpc.FutureTimeoutError
[2024-10-30T02:21:34.874Z] Traceback (most recent call last):
[2024-10-30T02:21:34.874Z]   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[2024-10-30T02:21:34.874Z]     return _run_code(code, main_globals, None,
[2024-10-30T02:21:34.874Z]   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[2024-10-30T02:21:34.874Z]     exec(code, run_globals)
[2024-10-30T02:21:34.874Z]   File "/home/g6552/.vscode-server/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/__main__.py", line 71, in <module>
[2024-10-30T02:21:34.874Z]     cli.main()
[2024-10-30T02:21:34.874Z]   File "/home/g6552/.vscode-server/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/../debugpy/server/cli.py", line 501, in main
[2024-10-30T02:21:34.874Z]     run()
[2024-10-30T02:21:34.874Z]   File "/home/g6552/.vscode-server/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/../debugpy/server/cli.py", line 351, in run_file
[2024-10-30T02:21:34.874Z]     runpy.run_path(target, run_name="__main__")
[2024-10-30T02:21:34.874Z]   File "/home/g6552/.vscode-server/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 310, in run_path
[2024-10-30T02:21:34.874Z]     return _run_module_code(code, init_globals, run_name, pkg_name=pkg_name, script_name=fname)
[2024-10-30T02:21:34.874Z]   File "/home/g6552/.vscode-server/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 127, in _run_module_code
[2024-10-30T02:21:34.874Z]     _run_code(code, mod_globals, init_globals, mod_name, mod_spec, pkg_name, script_name)
[2024-10-30T02:21:34.874Z]   File "/home/g6552/.vscode-server/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 118, in _run_code
[2024-10-30T02:21:34.874Z]     exec(code, run_globals)
[2024-10-30T02:21:34.874Z]   File "/usr/lib/azure-functions-core-tools-4/workers/python/3.10/LINUX/X64/worker.py", line 71, in <module>
[2024-10-30T02:21:34.874Z]     main.main()
[2024-10-30T02:21:34.874Z]   File "/usr/lib/azure-functions-core-tools-4/workers/python/3.10/LINUX/X64/azure_functions_worker/main.py", line 60, in main
[2024-10-30T02:21:34.874Z]     return asyncio.run(start_async(
[2024-10-30T02:21:34.874Z]   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
[2024-10-30T02:21:34.874Z]     return loop.run_until_complete(main)
[2024-10-30T02:21:34.875Z]   File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
[2024-10-30T02:21:34.875Z]     return future.result()
[2024-10-30T02:21:34.875Z]   File "/usr/lib/azure-functions-core-tools-4/workers/python/3.10/LINUX/X64/azure_functions_worker/main.py", line 72, in start_async
[2024-10-30T02:21:34.875Z]     disp = await dispatcher.Dispatcher.connect(host=host, port=port,
[2024-10-30T02:21:34.875Z]   File "/usr/lib/azure-functions-core-tools-4/workers/python/3.10/LINUX/X64/azure_functions_worker/dispatcher.py", line 134, in connect
[2024-10-30T02:21:34.875Z]     await disp._grpc_connected_fut
[2024-10-30T02:21:34.875Z]   File "/usr/lib/azure-functions-core-tools-4/workers/python/3.10/LINUX/X64/azure_functions_worker/dispatcher.py", line 955, in __poll_grpc
[2024-10-30T02:21:34.875Z]     grpc.channel_ready_future(channel).result(
[2024-10-30T02:21:34.875Z]   File "/usr/lib/azure-functions-core-tools-4/workers/python/3.10/LINUX/X64/grpc/_utilities.py", line 151, in result
[2024-10-30T02:21:34.875Z]     self._block(timeout)
[2024-10-30T02:21:34.875Z]   File "/usr/lib/azure-functions-core-tools-4/workers/python/3.10/LINUX/X64/grpc/_utilities.py", line 97, in _block
[2024-10-30T02:21:34.875Z]     raise grpc.FutureTimeoutError()
[2024-10-30T02:21:34.875Z] grpc.FutureTimeoutError
[2024-10-30T02:21:35.467Z] Language Worker Process exited. Pid=31647.
[2024-10-30T02:21:35.467Z] python3 exited with code 1 (0x1). grpc.FutureTimeoutError,    raise grpc.FutureTimeoutError(),grpc.FutureTimeoutError.
[2024-10-30T02:21:35.473Z] Exceeded language worker restart retry count for runtime:python. Shutting down and proactively recycling the Functions Host to recover
[2024-10-30T02:22:29.533Z] Starting worker process failed
[2024-10-30T02:22:29.533Z] Microsoft.Azure.WebJobs.Script.Grpc: The operation has timed out.
[2024-10-30T02:22:29.534Z] Failed to start language worker process for runtime: python. workerId:d838b59a-5155-4ab8-83f3-7a2a1e20bba5
[2024-10-30T02:22:29.581Z] No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
For detailed output, run func with --verbose flag.
 *  Terminal will be reused by tasks, press any key to close it. 
```

**Comment by bhagyshricompany** [comment]
Hi @yooontheearth Thanks for informing I checked seems its working,can you try via cmd like func  start port --9000 like this.![Image](https://github.com/user-attachments/assets/22491aaf-baa7-40db-983a-5555941202d9)

**Comment by yooontheearth** [comment]
Specifying the port didn't work on WSL, and attempt of running the function on Windows directly didn't work either. But for some reason, running the function on DevContainer worked. It may be because I use the following feature from DevContianer. Not sure at all.

```
"features": {
	"ghcr.io/jlaundry/devcontainer-features/azure-functions-core-tools:1": {}
},
```

**Comment by yooontheearth** [comment]
I was behind a corporation proxy server, so that might have blocked a connection. Unsure though.
