### ISSUE TITLE
Unable to execute Azure function with Azure Powershell script under App Service plan.

### ISSUE THREAD

**Issue by chandermani** [Azure/Azure-Functions#481]
I am trying to create a Azure storage backup solution using Azure functions & PowerShell Script.

```
$ErrorActionPreference = "Stop"
Write-Output "PowerShell Timer trigger function executed at:$(get-date)";
$context = "FUNCTIONNAME=$EXECUTION_CONTEXT_FUNCTIONNAME,FUNCTIONDIRECTORY=$EXECUTION_CONTEXT_FUNCTIONDIRECTORY" 
Write-Output $context

SET-LOCATION $EXECUTION_CONTEXT_FUNCTIONDIRECTORY

# Tables that need to be backedup. Coplete table will be backedup
$tablesRequiringBackup = @("tenantConfiguration", "migrationtracker")

$sourceAccountContext = New-AzureStorageContext -ConnectionString "$Env:AppMainStorageAccountConnectionString"

$targetAccountContext = New-AzureStorageContext -ConnectionString "$Env:AppMainStorageAccountBackupConnectionString"

$backupCountainerNameEndPoint = "$($targetAccountContext.BlobEndpoint)backup-" + (Get-Date).ToString("yyyy-MM-dd")

$tablesRequiringBackup| foreach {
	Write-Output "Backing up $_"
	Invoke-Expression "& '..\shared\backup-table.ps1' -tableName '$_' -sourceTableEndpoint '$($sourceAccountContext.TableEndpoint)' -targetContainer '$backupCountainerNameEndPoint' -sourceKey '$($sourceAccountContext.StorageAccount.Credentials.ExportBase64EncodedKey())' -targetKey '$($targetAccountContext.StorageAccount.Credentials.ExportBase64EncodedKey())'"
}
```
Function's like above are executed every X number of hours. I am unable to execute such functions in my App Service plan. The error that I receive is

` The term 'New-AzureStorageContext' is not recognized`

**This works fine when i restart the underlying service.** These scripts worked when the scripts were deployed under the **consumption plan**.

I looked at the issue webjobs-sdk issue https://github.com/Azure/azure-webjobs-sdk-script/issues/1426, and added these lines at the top of my script

```
Import-Module "D:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager\AzureRM.Profile\AzureRM.Profile.psd1" -Global; 
Import-Module "D:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager\AzureRM.Resources\AzureRM.Resources.psd1" -Global; 
Import-Module "D:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager\AzureRM.Automation\AzureRM.Automation.psd1" -Global;
Import-Module "D:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\Storage\Azure.Storage\Azure.Storage.psd1" -Global
```

But now I get another error instead.

```
Exception while executing function: Functions.backup-tenant-app-tables
Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: Functions.backup-tenant-app-tables ---> System.Management.Automation.CmdletInvocationException : Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index ---> System.ArgumentOutOfRangeException : Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.Collections.ArrayList.set_Item(Int32 index,Object value)
   at System.Collections.Specialized.OrderedDictionary.set_Item(Object key,Object value)
   at Microsoft.Azure.Commands.Common.Authentication.Factories.ClientFactory.AddHandler[T](T handler)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.SetupHttpClientPipeline()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.BeginProcessing()
   at System.Management.Automation.Cmdlet.DoBeginProcessing()
   at System.Management.Automation.CommandProcessorBase.DoBegin() 
   End of inner exception
   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar,Func`2 endFunction,Action`1 endAction,Task`1 promise,Boolean requiresSynchronization)
   at async Microsoft.Azure.WebJobs.Script.Description.PowerShellFunctionInvoker.InvokePowerShellScript(Dictionary`2 envVars,TraceWriter traceWriter) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Description\PowerShell\PowerShellFunctionInvoker.cs : 108
   at async Microsoft.Azure.WebJobs.Script.Description.PowerShellFunctionInvoker.InvokeCore(Object[] parameters,FunctionInvocationContext context) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\De…
```

Restarting the underlying service again fixes the issue. 

Please let me know if it a know issue, or else something that need to fix on my part.

**Comment by TVDKoni** [comment]
Same issue here. The error "The term 'New-AzureStorageContext' is not recognized" I had also in consumption plan. The error "Index was out of range" I only get in App Service Plan. Restarting the function app sometimes helps, sometimes not. Opened a MS ticket: 118030817774559

**Comment by alexkarcher-msft** [comment]
Our powershell support is still in an experimental support phase, and will be replaced by a ground up rework of our powershell worker soon. 

If you would like GA powershell support you can use Azure Automation.
