### ISSUE TITLE
BlobTrigger Javascript Error: Received message larger than max (11112848 vs. 4194304)

### ISSUE THREAD

**Issue by simonaco** [Azure/Azure-Functions#592]
Javascript BlobTrigger function fails with error message (see logs bellow). I am running on:
OSX
dotnet-core: v2.0.2
Azure Functions Core Tools (2.0.1-beta.21)
Function Runtime Version: 2.0.11370.0

Worker.Node.fdef4ba8-9c72-479f-8e6a-3e2af09cea5b[0]
      Worker fdef4ba8-9c72-479f-8e6a-3e2af09cea5b encountered event stream error:  { Error: Received message larger than max (11112848 vs. 4194304)
info: Worker.Node.fdef4ba8-9c72-479f-8e6a-3e2af09cea5b[0]
          at ClientDuplexStream._emitStatusIfDone (/Users/simonacotin/.azurefunctions/bin/workers/node/worker-bundle.js:22590:19)
info: Worker.Node.fdef4ba8-9c72-479f-8e6a-3e2af09cea5b[0]
          at ClientDuplexStream._receiveStatus (/Users/simonacotin/.azurefunctions/bin/workers/node/worker-bundle.js:22568:8)
info: Worker.Node.fdef4ba8-9c72-479f-8e6a-3e2af09cea5b[0]
          at /Users/simonacotin/.azurefunctions/bin/workers/node/worker-bundle.js:23092:12 code: 8, metadata: Metadata { _internal_repr: {} } }
info: Worker.Node.fdef4ba8-9c72-479f-8e6a-3e2af09cea5b[0]
      Worker fdef4ba8-9c72-479f-8e6a-3e2af09cea5b uncaught exception:  { Error: Received message larger than max (11112848 vs. 4194304)
info: Worker.Node.fdef4ba8-9c72-479f-8e6a-3e2af09cea5b[0]
          at ClientDuplexStream._emitStatusIfDone (/Users/simonacotin/.azurefunctions/bin/workers/node/worker-bundle.js:22590:19)
info: Worker.Node.fdef4ba8-9c72-479f-8e6a-3e2af09cea5b[0]
          at ClientDuplexStream._receiveStatus (/Users/simonacotin/.azurefunctions/bin/workers/node/worker-bundle.js:22568:8)
info: Worker.Node.fdef4ba8-9c72-479f-8e6a-3e2af09cea5b[0]
          at /Users/simonacotin/.azurefunctions/bin/workers/node/worker-bundle.js:23092:12 code: 8, metadata: Metadata { _internal_repr: {} } }

**Comment by christopheranderson** [comment]
This issue was moved to Azure/azure-webjobs-sdk-script#2136
