### ISSUE TITLE
Webjobs/Functions Extension upgrade corrupts VS2017 Preview Azure Functions capabilities

### ISSUE THREAD

**Issue by paulbatum** [Azure/Azure-Functions#594]
_From @brandonh-msft on October 5, 2017 18:10_

When running VS 2017 Preview, an update notification can be seen for the Webjobs & Functions Tools product. Performing this update will corrupt the Webjobs & Functions capabilities of VS2017.

#### Repro steps
1. Install VS 2017 Preview (15.4.0p4) with Azure Development workload
1. Run VS2017 Preview
1. Observe notification to update Azure Functions and Web Jobs Tools
1. Perform upgrade

#### Expected behavior
Upgrade completes successfully and VS 2017 still able to work w/ Azure Functions projects

#### Actual behavior
Upgrade fails in the VSIX installer with error in log akin to:

	10/5/2017 10:43:48 AM - Package 'Microsoft.VisualStudio.Web.AzureFunctions,version=15.0.30923.0' failed to install. System.IO.IOException: The file 'C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Common7\IDE\Extensions\Microsoft\Web Tools Azure\WebJobs\CLI\1.0.4\Azure.Functions.Cli.zip' already exists.
	   at Microsoft.VisualStudio.Setup.Installer.VsixInstaller.InstallCore(String localPath, String installDir, InstallablePackage pkg)
	   at Microsoft.VisualStudio.Setup.Installer.InstallerBase.InstallHelper(InstallData installData)
	10/5/2017 10:43:48 AM - Skipping cache of package 'Component.Microsoft.VisualStudio.Web.AzureFunctions,version=15.0.26720.2' since the package or a parent package had a vital failure.
	10/5/2017 10:43:48 AM - Skipping cache of package 'Microsoft.VisualStudio.ComponentGroup.AzureFunctions,version=15.0.26720.2' since the package or a parent package had a vital failure.
	10/5/2017 10:43:48 AM - Skipping cache of package 'Microsoft.VisualStudio.ComponentGroup.Azure.Prerequisites,version=15.0.26711.1' since the package or a parent package had a vital failure.
	10/5/2017 10:44:17 AM - Install Error : Microsoft.VisualStudio.Setup.PackageFailureException: Package 'Microsoft.VisualStudio.Web.AzureFunctions' failed to install
	   at Microsoft.VisualStudio.Setup.InstallOperation.Run(CancellationToken token)
	   at Microsoft.VisualStudio.Setup.Engine.RunOperation(InstallOperation installOperation, CancellationToken token, ExecuteAction action, ITelemetryOperation telemetryOperation)
	   at Microsoft.VisualStudio.Setup.Engine.RunCoreOperation(InstallOperation coreOperation, ExecuteAction action, ITelemetryOperation telemetryOperation, CancellationToken token)
	   at Microsoft.VisualStudio.Setup.Engine.Install(Product product, String destination, CancellationToken token)
	   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion, IInstalledExtension& newExtension)
	   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion)
	   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
	   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)

VS 2017 can no longer work with existing, or create new, Azure Functions projects

#### Known workarounds
None.

#### Related information 

| Product | Version |
| --- | ---: |
| VS 2017 | 15.4.0 preview 4
| VS Installer| 1.12.108.927
| Installed Azure Web Jobs and Functions Tools | 15.0.30915.0
| Target Web Jobs and Functions Tools | 15.0.30923.0

_Copied from original issue: Azure/azure-webjobs-sdk-extensions#311_

**Comment by paulbatum** [comment]
I moved this issue as its tooling related.

@vijayrkn any ideas?

**Comment by vijayrkn** [comment]
@brandonh-msft 
The latest version of tooling is 15.0.31114 - https://marketplace.visualstudio.com/items?itemName=VisualStudioWebandAzureTools.AzureFunctionsandWebJobsTools

Can you try if this issue with fixed with the latest update?

**Comment by jeffhollan** [comment]
Closing for now.  @brandonh-msft let us know if still seeing in latest version
