### ISSUE TITLE
Unable to use Microsoft.Azure.DocumentDB.Core with dotnet core Azure Function app

### ISSUE THREAD

**Issue by DavidJFowler** [Azure/Azure-Functions#653]
Visual Studio Enterprise 2017 v15.5.3
Azure Functions and Web Jobs Tools v15.0.40108.0

Create an Azure Function project (Azure Functions v2 Preview (.NET Core), HttpTrigger

Add a reference to Nuget package Microsoft.Azure.DocumentDB.Core v 1.7.1

Add a class to the project:

```
using Microsoft.Azure.Documents;

namespace FunctionApp2
{
    public class MyClass
    {
        public Document Document { get; set; }
    }
}
```

Attempt to build the project. Gives the error:

```
Error		System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
   at System.Reflection.RuntimeMethodInfo.GetParameters()
   at MakeFunctionJson.MethodInfoExtensions.GetDisabled(MethodInfo method)
   at MakeFunctionJson.MethodInfoExtensions.HasUnsuportedAttributes(MethodInfo method, String& error)
   at MakeFunctionJson.FunctionJsonConverter.TryGenerateFunctionJsons()
   at MakeFunctionJson.FunctionJsonConverter.TryRun()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

Error generating functions metadata
	FunctionApp2	C:\Users\xxxx\.nuget\packages\microsoft.net.sdk.functions\1.0.6\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets	32	

```

**Comment by cschwendtner** [comment]
@DavidJFowler The error is happening during the generation of function.json. 
Seems to be the same problem as in Azure/azure-functions-vs-build-sdk#115.

As a workaround you could try to change the access modifier of `MyClass` to internal or to move it into a separate project.

For more details see [my comment](https://github.com/Azure/azure-functions-vs-build-sdk/issues/150#issuecomment-354558283) on Azure/azure-functions-vs-build-sdk#150.

**Comment by jeffhollan** [comment]
Closing and will track view @cschwendtner issues noted above
