### ISSUE TITLE
System.IO.FileLoadException : Could not load file or assembly 'Microsoft.WindowsAzure.Storage, Version=8.7.0.0

### ISSUE THREAD

**Issue by valeriob** [Azure/Azure-Functions#679]
Hi,
I get this exception with this setup:
vs2017 with azure sdk, create new azure function, queue trigger, deploy, it works.
Now I add a reference to another nestandard2.0 project that references Microsoft.WindowsAzure.Storage, Version=8.7.0.0, deploy, and it fails with the following stacktrace.
I'm using this packages  : 
![image](https://user-images.githubusercontent.com/1522516/35750115-3600a830-0854-11e8-81fe-83f641c2e63b.png)

2018-02-02T19:00:25.133 ScriptHost initialization failed
2018-02-02T19:00:25.142 System.IO.FileLoadException : Could not load file or assembly 'Microsoft.WindowsAzure.Storage, Version=8.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621) ---> System.IO.FileLoadException : Could not load file or assembly 'Microsoft.WindowsAzure.Storage, Version=8.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext,String ilPath,String niPath,ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at System.Reflection.Assembly.LoadFromResolveHandler(Object sender,ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly,String assemblyFullName) 
   End of inner exception
   at System.Signature.GetSignature(Void* pCorSig,Int32 cCorSig,RuntimeFieldHandleInternal fieldHandle,IRuntimeMethodInfo methodHandle,RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
   at System.Reflection.RuntimeMethodInfo.GetParameters()
   at Microsoft.Azure.WebJobs.Script.UserTypeScanner.ScanMethod(Dictionary`2 possibleExtensionAssemblies,MethodInfo method) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\UserTypeScanner.cs : 33
   at Microsoft.Azure.WebJobs.Script.UserTypeScanner.GetPossibleExtensionAssemblies(IEnumerable`1 userTypes) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\UserTypeScanner.cs : 25
   at Microsoft.Azure.WebJobs.Script.ScriptHost.LoadDirectlyReferencesExtensions(IEnumerable`1 userTypes) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 776
   at Microsoft.Azure.WebJobs.Script.ScriptHost.Initialize() at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 535
   at Microsoft.Azure.WebJobs.Script.ScriptHost.Create(IScriptHostEnvironment environment,IScriptEventManager eventManager,ScriptHostConfiguration scriptConfig,ScriptSettingsManager settingsManager,ILoggerFactoryBuilder loggerFactoryBuilder,ProxyClientExecutor proxyClient) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 996

**Comment by valeriob** [comment]
Any idea how to run this code ? Am i doing something wrong ?

**Comment by cschwendtner** [comment]
I think the underlying problem is described in Azure/azure-functions-host#992.
Can you downgrade Microsoft.WindowsAzure.Storage to 8.6.0.0 and try again?

**Comment by NoahStahl** [comment]
I downgraded to 8.6.0 in the referenced projected and that resolved the error. That said, this is still a problem blocking update to latest package in referenced projects. Is there a configuration to allow use of 8.7.0?

**Comment by valeriob** [comment]
Yep it worked, the problem is guessing the right version 😄

**Comment by cschwendtner** [comment]
@NoahStahl - AFAIK it's not yet possible for "built-in" assemblies (assemblies that are referenced by Microsoft.Azure.WebJobs). But it is being worked on it - see #1319.

**Comment by cschwendtner** [comment]
@valeriob I think the easiest way is to look at the versions of the assemblies that are referenced (by default) by Microsoft.Azure.WebJobs.

![image](https://user-images.githubusercontent.com/22419197/35937932-fb29debe-0c47-11e8-94ce-5924ba651e67.png)

**Comment by valeriob** [comment]
thanks @cschwendtner but as you see from my picture, that version is calculated by nuget, mine said 8.7.0 😄 
Nuget says >= 7.2.1

![image](https://user-images.githubusercontent.com/1522516/35958424-0ffed2d2-0ca1-11e8-9d71-8984cbcf5c71.png)

**Comment by cschwendtner** [comment]
@valeriob My guess was that you installed `Microsoft.WindowsAzure.Storage 8.7.0` manually. So after creating an empty functions project (and updating to `Microsoft.NET.Sdk.Functions 1.0.7`) are you seeing `Microsoft.WindowsAzure.Storage 8.7.0` and not `Microsoft.WindowsAzure.Storage 8.6.0`?

Shouldn't you look at `Microsoft.Azure.WebJobs 3.0.0-beta4` and not at `Microsoft.Azure.WebJobs 2.1.0` (or am I missing something)?

![image](https://user-images.githubusercontent.com/22419197/35965918-95a3989e-0cbc-11e8-9d28-26f489289f1a.png)

**Comment by valeriob** [comment]
yep, my mistake ! the -prerelease flags was off 😄

**Comment by frankfajardo** [comment]
In our project, we're using `Microsoft.Azure.WebJobs.ServiceBus`. Its .NET Standard version relies on `v9.3.0` of `WindowsAzure.Storage`. Is there a way around this? We're trying to build Azure Function on .NET Standard 2.0

**Comment by ColbyTresness** [comment]
This category of problems is resolved with Azure Functions 2.x. Please reopen if you're still having issues.

**Comment by dejanberic** [comment]
What if I am forced to use Azure Functions 1.x? I still have this problem.
I am using some nuget packages which are not working on .net standard 2.0, only on .net 4.6.1

**Comment by ColbyTresness** [comment]
Unfortunately this class of issue won't be fixed in 1.x, since it required a pretty big rearchitecture to resolve, which happened in 2.x. In the future, we're looking into a way to support .net 4.6.1 in 2.x, but as of right now this isn't supported.
