### ISSUE TITLE
EventHub trigger stopped working after couple of days

### ISSUE THREAD

**Issue by sergsalo** [Azure/Azure-Functions#709]
EventHub trigger was working just fine for couple of days. Then stopped working and I needed to manually start it. After that - it started working again.

2018-03-07T19:31:31.235 [Info] Function started (Id=a5513b22-ea59-4654-addd-32812429791a) UK South region.

It is currently working. It happened also in US East region. We have other regions that didn't stop (at least yet), but I'm worried that they can stop at any moment. 

Currently, the disabled property is bound to "IS_DISABLED" app setting. I wonder if that has something to do with this odd behavior?

**Comment by sergsalo** [comment]
we pump data to App Insights and it clearly shows that 6:30-18:00 (UTC) we didn't receive Function Start, Function Completed events

 traces 
| where cloud_RoleName == "xxxxx-uksouth" 
| where operation_Name == "send_to_router"
| summarize count() by bin(timestamp, 30m)
| render timechart

![image](https://user-images.githubusercontent.com/242369/37114074-2484f28e-21fc-11e8-82ac-171d0aacdd1d.png)

**Comment by cgillum** [comment]
Thanks for the information. I did notice the following errors for your function app:

```
Microsoft.Azure.WebJobs.Host.Listeners.FunctionListenerException : The listener for function 'Functions.send_to_router' was unable to start. ---> System.TimeoutException : The operation did not complete within the allocated time 00:00:00 for object request1. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 Reference:b853bdc02cd44c2b88d1f5567d56d094_G8, TrackingId:N/A, Timestamp:3/7/2018 7:11:19 AM ---> System.TimeoutException : The operation did not complete within the allocated time 00:00:00 for object request1. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Amqp.AmqpServiceClient`1.RequestAsyncResult.<>c.<GetAsyncSteps>b__10_3(RequestAsyncResult thisPtr,IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result) 
   End of inner exception
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Common.AsyncResult`1.End(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.Amqp.AmqpServiceClient`1.RequestAsyncResult.End(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Amqp.AmqpServiceClient`1.EndRequest(IAsyncResult result,MethodData md,MethodCallMessage mcm)
   at Microsoft.ServiceBus.Messaging.Amqp.AmqpServiceClient`1.AmqpClientProxy.Invoke(MethodCallMessage mcm)
   at Microsoft.ServiceBus.Messaging.RealProxy.Invoke(Object[] args)
   at proxy_2.EndGetRuntimeInfo[T](IAsyncResult )
   at Microsoft.ServiceBus.Messaging.Amqp.AmqpEventHubClient.GetRuntimeInfoAsyncResult`1.<>c.<GetAsyncSteps>b__12_3(GetRuntimeInfoAsyncResult`1 thisPtr,IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Amqp.AmqpEventHubClient.<GetRuntimeInformationAsync>b__4_1(IAsyncResult r)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar,Func`2 endFunction,Action`1 endAction,Task`1 promise,Boolean requiresSynchronization)
   at async Microsoft.ServiceBus.Messaging.EventProcessorHost.InitializeAsync()
   at async Microsoft.ServiceBus.Messaging.EventProcessorHost.StartAsync()
   at async Microsoft.Azure.WebJobs.Host.Listeners.FunctionListener.StartAsync(CancellationToken cancellationToken) 
   End of inner exception
```

So it looks to me like there was an availability problem in your event hub. However, I only see a few instances of this error around 2018-03-07 07:11:20 UTC. This seems to roughly match the time you are seeing where your function is not running.

When you say you had to "manually start it", can you elaborate? There might be an issue in the functions runtime where we do not recover correctly for these types of errors.

**Comment by cgillum** [comment]
Looking into this more, I see that the function host stopped around 2018-03-07 07:06:53 UTC. I don't know why it stopped, but it restarted a few minutes later at which point the above error occurred. Because this (potentially transient) error occurred during the function indexing period, the function was disabled by the host and therefore didn't attempt to read any of your event hub messages.

Adding @paulbatum - I believe this general pattern of problems may be a known issue in the functions host.

FWIW this is version 1.0.11559.0 of the runtime.

**Comment by sergsalo** [comment]
@cgillum by "manually started" I meant - I clicked "Run" button.

**Comment by cgillum** [comment]
Thanks. Probably step 3 was the one that resolved the issue for you. We'll look into this further.

**Comment by cgillum** [comment]
It looks like this is actually a design issue in the functions host. Ideally we would not have silently swallowed the failure that prevented your function from getting initialized. I've opened a separate issue for tracking here: https://github.com/Azure/azure-functions-host/issues/2497.

Let me know if you have other questions about this.

BTW, were you able to find error traces in Application Insights related to this at the timestamp I mentioned previously?

**Comment by sergsalo** [comment]
I see next error in AppInsights: 

timestamp [UTC] | 2018-03-07T07:11:19.103Z
-- | --
  | problemId | System.TimeoutException at proxy_2.EndGetRuntimeInfo
  | type | System.TimeoutException
  | assembly | DynamicProxyAssembly.F4A75B89, Version=0.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
  | method | proxy_2.EndGetRuntimeInfo
  | outerType | Microsoft.Azure.WebJobs.Host.Listeners.FunctionListenerException
  | outerMessage | The listener for function 'Functions.send_to_router' was unable to start.
  | innermostType | System.TimeoutException
  | innermostMessage | The operation did not complete within the allocated time 00:00:00 for object request1. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101
  | severityLevel | 3
