### ISSUE TITLE
Blob Trigger - Event Hub Capture - Avro Issue

### ISSUE THREAD

**Issue by JRiggenbach** [Azure/Azure-Functions#723]
We're attempting to use an Azure Function with a Blob Trigger written in Node.js.  We are triggering on Azure Event Hub Capture files.  We are using the following schema, as per the MS document, but also the same schema we get from the getSchema via the Apache Avro Tools:

``` "type" : "record",
 "name" : "EventData",
 "namespace" : "Microsoft.ServiceBus.Messaging",
 "fields" : [ {
   "name" : "SequenceNumber",
   "type" : "long"
 }, {
   "name" : "Offset",
   "type" : "string"
 }, {
   "name" : "EnqueuedTimeUtc",
   "type" : "string"
 }, {
   "name" : "SystemProperties",
   "type" : {
     "type" : "map",
     "values" : [ "long", "double", "string", "bytes" ]
   }
 }, {
   "name" : "Properties",
   "type" : {
     "type" : "map",
     "values" : [ "long", "double", "string", "bytes", "null" ]
   }
 }, {
   "name" : "Body",
   "type" : [ "null", "bytes" ]
 } ]
```
The Azure Function has the datatype set to Binary, as noted in this [issue](https://github.com/Azure/Azure-Functions/issues/215)
However, The function bombs out with the following error

```
2018-03-19T19:23:47.752 [Error,CaptureBlobTrigger] Error: invalid union index
    at WrappedUnionType._read (D:\home\site\wwwroot\CaptureBlobTrigger\node_modules\avsc\lib\types.js:1454:11)
    at MapType._read (D:\home\site\wwwroot\CaptureBlobTrigger\node_modules\avsc\lib\types.js:1801:25)
    at RecordType.readEventData [as _read] (eval at <anonymous> (D:\home\site\wwwroot\CaptureBlobTrigger\node_modules\avsc\lib\types.js:2248:10), <anonymous>:8:8)
    at readValue (D:\home\site\wwwroot\CaptureBlobTrigger\node_modules\avsc\lib\types.js:2817:17)
    at RecordType.Type.fromBuffer (D:\home\site\wwwroot\CaptureBlobTrigger\node_modules\avsc\lib\types.js:575:13)
    at module.exports (D:\home\site\wwwroot\CaptureBlobTrigger\index.js:40:28)
    at D:\Program Files (x86)\SiteExtensions\Functions\1.0.11612\bin\azurefunctions\functions.js:106:24
```
I did open an issue up on the avsc github as well, but would appreciate any suggestions?  Thanks.

**Comment by JRiggenbach** [comment]
function.json
``` 
{
  "bindings": [
    {
      "name": "myBlob",
      "type": "blobTrigger",
      "dataType": "binary",
      "direction": "in",
      "path": "test/{name}",
      "connection": "AZURE_STORAGE_CONNECTION_STRING"
    }
  ],
  "disabled": false
}
```

index.js
```
const avro = require('avsc');

module.exports = function (context, myBlob) {
    context.log("JavaScript blob trigger function processed blob \n Name:", context.bindingData.name, "\n Blob Size:", myBlob.length, "Bytes");

    context.log("myBlob", JSON.stringify(myBlob));
    const schema = avro.Type.forSchema({
        "type": "record",
        "name": "EventData",
        "namespace": "Microsoft.ServiceBus.Messaging",
        "fields": [{
            "name": "SequenceNumber",
            "type": "long"
        }, {
            "name": "Offset",
            "type": "string"
        }, {
            "name": "EnqueuedTimeUtc",
            "type": "string"
        }, {
            "name": "SystemProperties",
            "type": {
                "type": "map",
                "values": ["long", "double", "string", "bytes"]
            }
        }, {
            "name": "Properties",
            "type": {
                "type": "map",
                "values": ["long", "double", "string", "bytes", "null"]
            }
        }, {
            "name": "Body",
            "type": ["null", "bytes"]
        }]
    });

    if (myBlob.length) {
        context.log(schema.fromBuffer(myBlob));
        context.done();
    }
};
```

**Comment by mcholste** [comment]
I am having a similar issue. However, I have noticed that the blob delivered to node.js is corrupt from the Azure trigger. The MD5 produced by this code differs from the MD5 observed when the blob is manually downloaded:
<pre>
module.exports = function(context, blob){
  var md5 = crypto.createHash('md5').update(blob).digest('hex');
  context.log("JavaScript blob trigger function processed blob \n Name:", context.bindingData.uri, "\n bize:", blob.length, "Bytes and MD5 ", md5);
  context.done();
}
</pre>
This is 100% reproducible both with dataType set to binary or without.

**Comment by ColbyTresness** [comment]
Can you still repro this? Sorry for the delay

**Comment by ColbyTresness** [comment]
Closing due to lack of response. Please reopen if still experiencing issue.

**Comment by zhamadagithub** [comment]
I'm receiving this error: truncated bufferat RecordType.Type.fromBuffer when trying same code. Azure function Trigger on azure blob being added.
