### ISSUE TITLE
Unable to install version 15.0.40617.0 of 'Azure Functions and Web Jobs Tools' for VS 2017 15.8.0 Preview 2.0

### ISSUE THREAD

**Issue by ChristianWeyer** [Azure/Azure-Functions#850]
I do have VS 2017 15.8.0 Preview 2.0 installed.
When I try to install the latest Azure Functions and Web Jobs Tools, I get this:

![image](https://user-images.githubusercontent.com/888718/41721695-e2a7b432-7566-11e8-87e2-0ab714c7644f.png)

Here is the log file:
```
6/21/2018 3:17:28 PM - Microsoft VSIX Installer
6/21/2018 3:17:29 PM - -------------------------------------------
6/21/2018 3:17:29 PM - vsixinstaller.exe version:
6/21/2018 3:17:29 PM - 15.8.110
6/21/2018 3:17:29 PM - -------------------------------------------
6/21/2018 3:17:29 PM - Command line parameters:
6/21/2018 3:17:29 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,\\Mac\Home\Downloads\Microsoft.VisualStudio.Web.AzureFunctions (1).vsix
6/21/2018 3:17:29 PM - -------------------------------------------
6/21/2018 3:17:29 PM - Microsoft VSIX Installer
6/21/2018 3:17:29 PM - -------------------------------------------
6/21/2018 3:17:31 PM - Initializing Install...
6/21/2018 3:17:32 PM - Extension Details...
6/21/2018 3:17:32 PM - 	Identifier         : Microsoft.VisualStudio.Web.AzureFunctions
6/21/2018 3:17:32 PM - 	Name               : Azure Functions and Web Jobs Tools
6/21/2018 3:17:32 PM - 	Author             : Microsoft
6/21/2018 3:17:32 PM - 	Version            : 15.0.40617.0
6/21/2018 3:17:32 PM - 	Description        : Tools for creating and publishing Azure Functions and Web Jobs
6/21/2018 3:17:32 PM - 	Locale             : en-US
6/21/2018 3:17:32 PM - 	MoreInfoURL        : 
6/21/2018 3:17:32 PM - 	InstalledByMSI     : False
6/21/2018 3:17:32 PM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
6/21/2018 3:17:32 PM - 
6/21/2018 3:17:34 PM - 	SignatureState     : ValidSignature
6/21/2018 3:17:34 PM - 	SignedBy           : Microsoft Corporation
6/21/2018 3:17:34 PM - 	Certificate Info   : 
6/21/2018 3:17:34 PM - 		-------------------------------------------------------
6/21/2018 3:17:34 PM - 		[Subject]       : CN=Microsoft Corporation, OU=OPC, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
6/21/2018 3:17:34 PM - 		[Issuer]        : CN=Microsoft Code Signing PCA 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
6/21/2018 3:17:34 PM - 		[Serial Number] : 33000001FC5DB8191027A666C10000000001FC
6/21/2018 3:17:34 PM - 		[Not Before]    : 10/5/2017 8:26:08 PM
6/21/2018 3:17:34 PM - 		[Not After]     : 10/5/2018 8:26:08 PM
6/21/2018 3:17:34 PM - 		[Thumbprint]    : 5E940B33DEAE5945F506ADAB946A997867A40FEF
6/21/2018 3:17:34 PM - 
6/21/2018 3:17:34 PM - 	Supported Products : 
6/21/2018 3:17:34 PM - 		Microsoft.VisualStudio.Community
6/21/2018 3:17:34 PM - 			Version : [15.0.27421.1,15.0.27706.0)
6/21/2018 3:17:34 PM - 
6/21/2018 3:17:34 PM - 	References         : 
6/21/2018 3:17:34 PM - 	Prerequisites      : 
6/21/2018 3:17:34 PM - 		-------------------------------------------------------
6/21/2018 3:17:34 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
6/21/2018 3:17:34 PM - 		Name         : Visual Studio core editor
6/21/2018 3:17:34 PM - 		Version      : [15.0,16.0)
6/21/2018 3:17:34 PM - 
6/21/2018 3:17:34 PM - 		-------------------------------------------------------
6/21/2018 3:17:34 PM - 		Identifier   : Microsoft.VisualStudio.Component.Web
6/21/2018 3:17:34 PM - 		Name         : ASP.NET and web development tools
6/21/2018 3:17:34 PM - 		Version      : [15.0.26504,16.0)
6/21/2018 3:17:34 PM - 
6/21/2018 3:17:34 PM - Signature Details...
6/21/2018 3:17:34 PM - 	Extension is signed with a valid signature.
6/21/2018 3:17:34 PM - 
6/21/2018 3:17:34 PM - Searching for applicable products...
6/21/2018 3:17:34 PM - Found installed product - Global Location
6/21/2018 3:17:34 PM - Found installed product - ssms
6/21/2018 3:17:34 PM - Found installed product - Visual Studio Enterprise 2017 Preview
6/21/2018 3:17:34 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

```

**Comment by jeffhollan** [comment]
@cartermp if you can help look into this one as well

**Comment by cartermp** [comment]
This is currently by design, as the latest VSIX is only supported on non-preview releases of Visual Studio, due to requirements with VS 15.8 and setup authoring with AsyncPackage. Since the latest version is more of a servicing update to support .NET Core 2.1 and the self-contained bits in the functions feed, we did not make changes to have it installable in both VS release trains. When VS 15.8 is released, the functions tools that come with it will work.

That said, it appears I had incorrect information in the [Release notes](https://github.com/Azure/Azure-Functions/blob/master/VS-AzureTools-ReleaseNotes.md), indicating that for Preview 2 or lower, it would work. I'll update them.

**Comment by ChristianWeyer** [comment]
Thanks for the update!
I am quite sure there was a version of that VSIX that worked with 15.8... 🤔
