### ISSUE TITLE
Create linux app using azure CLI fails with "cannot import name 'get_sku_name'"

### ISSUE THREAD

**Issue by balag0** [Azure/Azure-Functions#855]
az functionapp createpreviewapp -n cotresnelinuxbugbash4  -g cotresnelinuxbugbash4 -l "WestUS" -s cotresnelinuxbugbash4 --runtime node --is-linux 

cannot import name 'get_sku_name' 

Traceback (most recent call last): 

  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\knack\cli.py", line 194, in invoke 

    cmd_result = self.invocation.execute(args) 

  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 241, in execute 

    self.commands_loader.load_arguments(command) 

  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\__init__.py", line 201, in load_arguments 

    self.command_table[command].load_arguments()  # this loads the arguments via reflection 

  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 142, in load_arguments 

    super(AzCliCommand, self).load_arguments() 

  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\knack\commands.py", line 76, in load_arguments 

    cmd_args = self.arguments_loader() 

  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\__init__.py", line 341, in default_arguments_loader 

    op = handler or self.get_op_handler(operation) 

  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\__init__.py", line 385, in get_op_handler 

    op = import_module(mod_to_import) 

  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\importlib\__init__.py", line 126, in import_module 

    return _bootstrap._gcd_import(name[level:], package, level) 

  File "<frozen importlib._bootstrap>", line 978, in _gcd_import 

  File "<frozen importlib._bootstrap>", line 961, in _find_and_load 

  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked 

  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked 

  File "<frozen importlib._bootstrap_external>", line 678, in exec_module 

  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed 

  File "C:\Users\cotresne\.azure\cliextensions\functionapp\azext_functionapp\custom.py", line 23, in <module> 

    from azure.cli.command_modules.appservice.custom import ( 

ImportError: cannot import name 'get_sku_name'

**Comment by dariagrigoriu** [comment]
No repro at this time.
