### ISSUE TITLE
Visual Studio publish fails when recreating a deleted resource group

### ISSUE THREAD

**Issue by ggailey777** [Azure/Azure-Functions#894]
## Repro
1. Follow the [Functions Visual Studio quickstart](https://docs.microsoft.com/azure/azure-functions/functions-create-your-first-function-visual-studio) to create and publish a new function app. This creates a function app, storage account, and plan in the `myresourcegroup` group.
2. Delete the `myresourcegroup` group.
3. Complete the [Functions Visual Studio quickstart](https://docs.microsoft.com/azure/azure-functions/functions-create-your-first-function-visual-studio) a second time, using the same `myresourcegroup` group name.

## Result

**Expected:** The `myresourcegroup` group is created and resources successfully publish as before. 
**Actual:** The following error occurs:
```
System.Net.Http.HttpRequestException
   at Microsoft.VisualStudio.Web.WindowsAzure.Provisioning.DeploymentManager.<ThrowOnUnexpectedStatusCode>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Client.ARMCaller.HttpResponseExtensions.<DeserializeEntityJsonAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Client.ARMCaller.EntityExtensions.<ReloadAsync>d__27`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.Web.WindowsAzure.Provisioning.DeploymentManager.<BeginDeployment>d__14.MoveNext()
```

## Comment
Troubleshooting info from @cjaliaga:

> Quick question, are you always trying to use “myresourcegroup” as resource group? Do you see the same error if you use a different resource group? I’ve been taking a look into the App Services Telemetry and I see some problems related to the Web Space the Resource Group is currently associated with: myresourcegroup-CentralUSwebspace
> 
> If you didn’t already, could you please try to do it using a  brand new resource group, one that you didn’t use already on this sub?

That did fix my deployment error. It seems that publishing artifacts are being left behind in my subscription when I delete the resource group. Many of our tutorials use `myresourcegroup` as the RG name, so it’s likely that customers will run into these collisions as they use our documentation.

## Versions
VS 2017: 15.7.5
Functions tools: 15.0.40617.0
Windows

**Comment by ColbyTresness** [comment]
I don't think this is a visual studio issue actually - it's more of a race condition on deletion and creation where Azure hasn't fully finished deleting but we mark as deleted. I've seen something similar when deleting and creating Function Apps. Not sure what can be done, but maybe @cgillum would know more. Closing though since this isn't a VS issue, we should track elsewhere
