### ISSUE TITLE
The operation did not complete within the allocated time 00:01:00 for object session98

### ISSUE THREAD

**Issue by grik001** [Azure/Azure-Functions#977]
Hi,

I am running an AzureFunction V1 with EventHub trigger. I randomly get the below errors:

System.TimeoutException

Microsoft.ServiceBus.Common.AsyncResult.End

`The operation did not complete within the allocated time 00:01:00 for object session98. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101`

```
EventProcessorHost error (Action=Close) : System.TimeoutException: The operation did not complete within the allocated time 00:01:00 for object session98. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101
 at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
 at Microsoft.ServiceBus.Messaging.Amqp.AmqpObject.EndClose(IAsyncResult result)
 at Microsoft.ServiceBus.Messaging.Amqp.AmqpMessagingFactory.CloseEntityAsyncResult.<>c.<GetAsyncSteps>b__2_1(CloseEntityAsyncResult thisPtr, IAsyncResult r)
 at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
 --- End of stack trace from previous location where exception was thrown ---
 at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
 at Microsoft.ServiceBus.Messaging.Amqp.AmqpMessageReceiver.OnEndClose(IAsyncResult result)
 at Microsoft.ServiceBus.Messaging.ClientEntity.EndClose(IAsyncResult result)
 at Microsoft.ServiceBus.Messaging.EventHubReceiver.OnEndClose(IAsyncResult result)
 at Microsoft.ServiceBus.Messaging.ClientEntity.EndClose(IAsyncResult result)
 at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.ServiceBus.Common.TaskHelpers.EndAsyncResult(IAsyncResult asyncResult)
 at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.<>c.<CallTask>b__24_1(TIteratorAsyncResult thisPtr, IAsyncResult r)
 at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

```
Stack:

```
System.TimeoutException:
   at Microsoft.ServiceBus.Common.AsyncResult.End (Microsoft.ServiceBus, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.ServiceBus.Messaging.Amqp.AmqpObject.EndClose (Microsoft.ServiceBus, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.ServiceBus.Messaging.Amqp.AmqpMessagingFactory+CloseEntityAsyncResult+<>c.<GetAsyncSteps>b__2_1 (Microsoft.ServiceBus, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback (Microsoft.ServiceBus, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.ServiceBus.Common.AsyncResult.End (Microsoft.ServiceBus, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.ServiceBus.Messaging.Amqp.AmqpMessageReceiver.OnEndClose (Microsoft.ServiceBus, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.ServiceBus.Messaging.ClientEntity.EndClose (Microsoft.ServiceBus, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.ServiceBus.Messaging.EventHubReceiver.OnEndClose (Microsoft.ServiceBus, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.ServiceBus.Messaging.ClientEntity.EndClose (Microsoft.ServiceBus, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at Microsoft.ServiceBus.Common.TaskHelpers.EndAsyncResult (Microsoft.ServiceBus, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1+<>c.<CallTask>b__24_1 (Microsoft.ServiceBus, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback (Microsoft.ServiceBus, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)

```

**Comment by pragnagopa** [comment]
Closing this as we have existing issue https://github.com/Azure/azure-webjobs-sdk/issues/1597 tracking adding support to configure retries with eventhub trigger
