### ISSUE TITLE
Microsoft.ServiceBus.Messaging.ReceiverDisconnectedException

### ISSUE THREAD

**Issue by grik001** [Azure/Azure-Functions#979]
Hi 

I am receiving the following errors when running an Azure Function V1 with EventHub. 

I am not sure if the following issues are related, feel free to delete any issues if they are.

#978 #977 

`New receiver with higher epoch of '30' is created hence current receiver with epoch '29' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:f86cbdf9000065ee0112a3dd5bb5a5f2_C-1363158168_B24, SystemTracker:invictus-stg-we-sft-evnm:eventhub:invictus-stg-we-sft-evhb~1023\|$default, Timestamp:10/4/2018 5:41:34 AM`

```
EventProcessorHost error (Action=Receive) : Microsoft.ServiceBus.Messaging.ReceiverDisconnectedException: New receiver with higher epoch of '30' is created hence current receiver with epoch '29' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:f86cbdf9000065ee0112a3dd5bb5a5f2_C-1363158168_B24, SystemTracker:invictus-stg-we-sft-evnm:eventhub:invictus-stg-we-sft-evhb~1023|$default, Timestamp:10/4/2018 5:41:34 AM
 at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
 at Microsoft.ServiceBus.Messaging.MessageReceiver.RetryReceiveEventDataAsyncResult.TryReceiveEnd(IAsyncResult r, IEnumerable`1& messages)
 at Microsoft.ServiceBus.Messaging.MessageReceiver.EndTryReceiveEventData(IAsyncResult result, IEnumerable`1& messages)
 at Microsoft.ServiceBus.Messaging.EventHubReceiver.<ReceiveAsync>b__56_1(IAsyncResult result)
 at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.ServiceBus.Common.TaskHelpers.EndAsyncResult(IAsyncResult asyncResult)
 at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.<>c.<CallTask>b__24_1(TIteratorAsyncResult thisPtr, IAsyncResult r)
 at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
```

Stack

```
Microsoft.ServiceBus.Messaging.ReceiverDisconnectedException:
   at Microsoft.ServiceBus.Common.AsyncResult.End (Microsoft.ServiceBus, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.ServiceBus.Messaging.MessageReceiver+RetryReceiveEventDataAsyncResult.TryReceiveEnd (Microsoft.ServiceBus, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.ServiceBus.Messaging.MessageReceiver.EndTryReceiveEventData (Microsoft.ServiceBus, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.ServiceBus.Messaging.EventHubReceiver.<ReceiveAsync>b__56_1 (Microsoft.ServiceBus, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at Microsoft.ServiceBus.Common.TaskHelpers.EndAsyncResult (Microsoft.ServiceBus, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1+<>c.<CallTask>b__24_1 (Microsoft.ServiceBus, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback (Microsoft.ServiceBus, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
```

**Comment by pragnagopa** [comment]
From the discussion [here](https://social.msdn.microsoft.com/Forums/azure/en-US/f89ade2f-c695-42e6-944b-6a744f081f90/is-there-a-recommanded-way-to-handle-microsoftservicebusmessagingreceiverdisconnectedexception?forum=servbus), this exception seems to be harmless.  Are you seeing a high number of these exceptions?

**Comment by grik001** [comment]
Yes, when running a job with huge load the logs are bloated with these errors.

**Comment by pragnagopa** [comment]
Tracking issue https://github.com/Azure/azure-webjobs-sdk/issues/1947
